// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/infobloxopen/atlas-contacts-app/proto/contacts.proto

/*
Package github.com/infobloxopen/atlas-contacts-app/orm is a generated protocol buffer package.

It is generated from these files:
	github.com/infobloxopen/atlas-contacts-app/proto/contacts.proto

It has these top-level messages:
	Contact
	ContactPage
	SearchRequest
	GetRequest
	SMSRequest
*/
package contacts

import contacts1 "github.com/infobloxopen/atlas-contacts-app/pb/contacts"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Contact no comment was provided for message type
type Contact struct {
	ID         uint64
	FirstName  string
	MiddleName string
	LastName   string
	//proto: missing extension
	EmailAddress string
}

// ConvertToContact takes a pb object and returns an orm object
func ConvertToContact(from contacts1.Contact) Contact {
	to := Contact{}
	to.ID = from.Id
	to.FirstName = from.FirstName
	to.MiddleName = from.MiddleName
	to.LastName = from.LastName
	to.EmailAddress = from.EmailAddress
	return to
}

// ConvertFromContact takes an orm object and returns a pb object
func ConvertFromContact(from Contact) contacts1.Contact {
	to := contacts1.Contact{}
	to.Id = from.ID
	to.FirstName = from.FirstName
	to.MiddleName = from.MiddleName
	to.LastName = from.LastName
	to.EmailAddress = from.EmailAddress
	return to
}
