sudo: required

services:
  - docker

language: go

go:
  - "1.16"

before_install:

install:
  # vendor the go dependencies
  - make vendor

script:
  # run the unit and integration tests
  - make test-with-integration
