apiVersion: infoblox.com/v1
kind: SubjectGroup
metadata:
  name: all-users
  namespace: authz
  labels:
    pargset: authz
criteria:
  type: User
---
apiVersion: infoblox.com/v1
kind: SubjectGroup
metadata:
  name: engineers
  namespace: authz
  labels:
    pargset: authz
criteria:
  type: User
  department: Engineering
---
apiVersion: infoblox.com/v1
kind: Assoc
metadata:
  name: contacts-all-users
  namespace: contacts
  labels:
    pargset: authz
group: all-users
role: contacts-read-only
---
apiVersion: infoblox.com/v1
kind: Assoc
metadata:
  name: contacts-admin
  namespace: contacts
  labels:
    pargset: authz
group: engineers
role: contacts-read-write
---
apiVersion: infoblox.com/v1
kind: Role
metadata:
  name: contacts-read-only
  namespace: contacts
  labels:
    pargset: authz
permissions:
  - contacts-read
---
apiVersion: infoblox.com/v1
kind: Role
metadata:
  name: contacts-read-write
  namespace: contacts
  labels:
    pargset: authz
permissions:
  - contacts-read
  - contacts-write
---
apiVersion: infoblox.com/v1
kind: Permission
metadata:
  name: contacts-read
  namespace: contacts
  labels:
    pargset: authz
operations:
  - Contacts.List
  - Contacts.Get
---
apiVersion: infoblox.com/v1
kind: Permission
metadata:
  name: contacts-write
  namespace: contacts
  labels:
    pargset: authz
operations:
  - Contacts.Create
  - Contacts.Update
  - Contacts.Delete
  - Contacts.SendSMS
