// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/infobloxopen/atlas-contacts-app/proto/contacts.proto

/*
Package contacts is a generated protocol buffer package.

It is generated from these files:
	github.com/infobloxopen/atlas-contacts-app/proto/contacts.proto

It has these top-level messages:
	Contact
	TagCondition
	TagQuery
	PagingOptions
	SearchCriteria
	SearchRequest
	ContactPage
*/
package contacts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Contact struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName    string `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	MiddleName   string `protobuf:"bytes,3,opt,name=middle_name,json=middleName" json:"middle_name,omitempty"`
	LastName     string `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	EmailAddress string `protobuf:"bytes,5,opt,name=email_address,json=emailAddress" json:"email_address,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Contact) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contact) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Contact) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Contact) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Contact) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type TagCondition struct {
	Tag   string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Op    string `protobuf:"bytes,2,opt,name=op" json:"op,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *TagCondition) Reset()                    { *m = TagCondition{} }
func (m *TagCondition) String() string            { return proto.CompactTextString(m) }
func (*TagCondition) ProtoMessage()               {}
func (*TagCondition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TagCondition) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *TagCondition) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *TagCondition) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TagQuery struct {
	Conditions []*TagCondition `protobuf:"bytes,1,rep,name=conditions" json:"conditions,omitempty"`
}

func (m *TagQuery) Reset()                    { *m = TagQuery{} }
func (m *TagQuery) String() string            { return proto.CompactTextString(m) }
func (*TagQuery) ProtoMessage()               {}
func (*TagQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TagQuery) GetConditions() []*TagCondition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type PagingOptions struct {
	Limit  uint32 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Start  uint32 `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	Offset uint32 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Total  uint32 `protobuf:"varint,4,opt,name=total" json:"total,omitempty"`
}

func (m *PagingOptions) Reset()                    { *m = PagingOptions{} }
func (m *PagingOptions) String() string            { return proto.CompactTextString(m) }
func (*PagingOptions) ProtoMessage()               {}
func (*PagingOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PagingOptions) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PagingOptions) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *PagingOptions) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PagingOptions) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type SearchCriteria struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName    string `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	MiddleName   string `protobuf:"bytes,3,opt,name=middle_name,json=middleName" json:"middle_name,omitempty"`
	LastName     string `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	EmailAddress string `protobuf:"bytes,5,opt,name=email_address,json=emailAddress" json:"email_address,omitempty"`
}

func (m *SearchCriteria) Reset()                    { *m = SearchCriteria{} }
func (m *SearchCriteria) String() string            { return proto.CompactTextString(m) }
func (*SearchCriteria) ProtoMessage()               {}
func (*SearchCriteria) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SearchCriteria) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchCriteria) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SearchCriteria) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *SearchCriteria) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SearchCriteria) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type SearchRequest struct {
	Criteria *SearchCriteria `protobuf:"bytes,1,opt,name=criteria" json:"criteria,omitempty"`
	Paging   *PagingOptions  `protobuf:"bytes,2,opt,name=paging" json:"paging,omitempty"`
	Tags     *TagQuery       `protobuf:"bytes,3,opt,name=tags" json:"tags,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SearchRequest) GetCriteria() *SearchCriteria {
	if m != nil {
		return m.Criteria
	}
	return nil
}

func (m *SearchRequest) GetPaging() *PagingOptions {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *SearchRequest) GetTags() *TagQuery {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ContactPage struct {
	Paging   *PagingOptions `protobuf:"bytes,1,opt,name=paging" json:"paging,omitempty"`
	Contacts []*Contact     `protobuf:"bytes,2,rep,name=contacts" json:"contacts,omitempty"`
}

func (m *ContactPage) Reset()                    { *m = ContactPage{} }
func (m *ContactPage) String() string            { return proto.CompactTextString(m) }
func (*ContactPage) ProtoMessage()               {}
func (*ContactPage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ContactPage) GetPaging() *PagingOptions {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *ContactPage) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func init() {
	proto.RegisterType((*Contact)(nil), "api.contacts.Contact")
	proto.RegisterType((*TagCondition)(nil), "api.contacts.TagCondition")
	proto.RegisterType((*TagQuery)(nil), "api.contacts.TagQuery")
	proto.RegisterType((*PagingOptions)(nil), "api.contacts.PagingOptions")
	proto.RegisterType((*SearchCriteria)(nil), "api.contacts.SearchCriteria")
	proto.RegisterType((*SearchRequest)(nil), "api.contacts.SearchRequest")
	proto.RegisterType((*ContactPage)(nil), "api.contacts.ContactPage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Contacts service

type ContactsClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ContactPage, error)
	Create(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Contact, error)
	Get(ctx context.Context, in *SearchCriteria, opts ...grpc.CallOption) (*Contact, error)
	Update(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Contact, error)
	Delete(ctx context.Context, in *SearchCriteria, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type contactsClient struct {
	cc *grpc.ClientConn
}

func NewContactsClient(cc *grpc.ClientConn) ContactsClient {
	return &contactsClient{cc}
}

func (c *contactsClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ContactPage, error) {
	out := new(ContactPage)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Create(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Contact, error) {
	out := new(Contact)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Get(ctx context.Context, in *SearchCriteria, opts ...grpc.CallOption) (*Contact, error) {
	out := new(Contact)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Update(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*Contact, error) {
	out := new(Contact)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Delete(ctx context.Context, in *SearchCriteria, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Contacts service

type ContactsServer interface {
	Search(context.Context, *SearchRequest) (*ContactPage, error)
	Create(context.Context, *Contact) (*Contact, error)
	Get(context.Context, *SearchCriteria) (*Contact, error)
	Update(context.Context, *Contact) (*Contact, error)
	Delete(context.Context, *SearchCriteria) (*google_protobuf.Empty, error)
}

func RegisterContactsServer(s *grpc.Server, srv ContactsServer) {
	s.RegisterService(&_Contacts_serviceDesc, srv)
}

func _Contacts_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Create(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCriteria)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Get(ctx, req.(*SearchCriteria))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Update(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCriteria)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Delete(ctx, req.(*SearchCriteria))
	}
	return interceptor(ctx, in, info, handler)
}

var _Contacts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.contacts.Contacts",
	HandlerType: (*ContactsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Contacts_Search_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Contacts_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Contacts_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Contacts_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Contacts_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/infobloxopen/atlas-contacts-app/proto/contacts.proto",
}

func init() {
	proto.RegisterFile("github.com/infobloxopen/atlas-contacts-app/proto/contacts.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 802 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xc1, 0x8e, 0xe3, 0x44,
	0x10, 0xc5, 0x76, 0xe2, 0x49, 0x2a, 0x71, 0x14, 0x9a, 0x25, 0x24, 0xce, 0x22, 0x22, 0x73, 0x89,
	0x22, 0x62, 0xb3, 0xde, 0x0b, 0xca, 0x1e, 0x60, 0x13, 0x58, 0x24, 0x84, 0x60, 0xd7, 0xbb, 0x70,
	0x40, 0x42, 0x4b, 0xc7, 0xee, 0x38, 0xbd, 0xb2, 0xdd, 0xc6, 0xee, 0xcc, 0x30, 0x42, 0x5c, 0xf8,
	0x04, 0xb8, 0x70, 0xe6, 0x88, 0x10, 0xf7, 0x99, 0x13, 0xff, 0xc0, 0x2f, 0xcc, 0x01, 0xfe, 0x02,
	0xb9, 0xdb, 0xce, 0x24, 0x33, 0x01, 0x66, 0x2e, 0xdc, 0xba, 0xaa, 0x5e, 0xbd, 0x7a, 0x55, 0x95,
	0x94, 0xe1, 0xdd, 0x90, 0xf2, 0xf5, 0x66, 0x69, 0xfb, 0x2c, 0x76, 0x68, 0xb2, 0x62, 0xcb, 0x88,
	0x7d, 0xc3, 0x52, 0x92, 0x38, 0x98, 0x47, 0x38, 0x9f, 0xfa, 0x2c, 0xe1, 0xd8, 0xe7, 0xf9, 0x14,
	0xa7, 0xa9, 0x93, 0x66, 0x8c, 0x33, 0xa7, 0x72, 0xd9, 0xc2, 0x44, 0x6d, 0x9c, 0x52, 0xbb, 0xf2,
	0x99, 0xc3, 0x90, 0xb1, 0x30, 0x22, 0x12, 0xba, 0xdc, 0xac, 0x1c, 0x12, 0xa7, 0xfc, 0x54, 0x42,
	0xcd, 0xbb, 0x65, 0x10, 0xa7, 0xd4, 0xc1, 0x49, 0xc2, 0x38, 0xe6, 0x94, 0x25, 0x25, 0x91, 0xf9,
	0x60, 0x47, 0x49, 0x74, 0xba, 0xe2, 0x92, 0xc3, 0x9f, 0x86, 0x24, 0x99, 0x1e, 0xe3, 0x88, 0x06,
	0x98, 0x13, 0xe7, 0xda, 0xa3, 0x4c, 0x7e, 0x6b, 0x07, 0x9c, 0x9f, 0xe0, 0x30, 0x24, 0x99, 0xc3,
	0x52, 0x41, 0x7f, 0xa0, 0x94, 0xc1, 0xb2, 0xd8, 0x61, 0x59, 0x2c, 0x4d, 0xeb, 0x37, 0x05, 0x8e,
	0x16, 0xb2, 0x03, 0xd4, 0x01, 0x95, 0x06, 0x7d, 0x65, 0xa4, 0x8c, 0x6b, 0x9e, 0x4a, 0x03, 0xf4,
	0x3a, 0xc0, 0x8a, 0x66, 0x39, 0x7f, 0x9e, 0xe0, 0x98, 0xf4, 0xd5, 0x91, 0x32, 0x6e, 0x7a, 0x4d,
	0xe1, 0xf9, 0x04, 0xc7, 0x04, 0xbd, 0x01, 0xad, 0x98, 0x06, 0x41, 0x44, 0x64, 0x5c, 0x13, 0x71,
	0x90, 0x2e, 0x01, 0x18, 0x42, 0x33, 0xc2, 0x55, 0x7a, 0x4d, 0x84, 0x1b, 0x85, 0x43, 0x04, 0x6d,
	0x30, 0x48, 0x8c, 0x69, 0xf4, 0x1c, 0x07, 0x41, 0x46, 0xf2, 0xbc, 0x5f, 0x2f, 0x00, 0xf3, 0xe6,
	0xf9, 0x5f, 0xbf, 0x6b, 0xb5, 0x4c, 0xfd, 0x4a, 0xf1, 0xda, 0x22, 0xfe, 0x50, 0x86, 0x67, 0xfa,
	0xf9, 0xd9, 0x40, 0x6d, 0x28, 0xd6, 0x23, 0x68, 0x3f, 0xc3, 0xe1, 0x82, 0x25, 0x01, 0x2d, 0xda,
	0x42, 0x5d, 0xd0, 0x38, 0x0e, 0x85, 0xea, 0xa6, 0x57, 0x3c, 0x8b, 0x36, 0x58, 0x5a, 0xca, 0x55,
	0x59, 0x8a, 0xee, 0x40, 0xfd, 0x18, 0x47, 0x9b, 0x4a, 0xa1, 0x34, 0xac, 0x47, 0xd0, 0x78, 0x86,
	0xc3, 0x27, 0x1b, 0x92, 0x9d, 0xa2, 0x19, 0x80, 0x5f, 0x11, 0xe6, 0x7d, 0x65, 0xa4, 0x8d, 0x5b,
	0xae, 0x69, 0xef, 0x2e, 0xd7, 0xde, 0xad, 0xe9, 0xed, 0xa0, 0xad, 0x13, 0x30, 0x1e, 0xe3, 0x90,
	0x26, 0xe1, 0xa7, 0x72, 0xe4, 0xc8, 0x82, 0x7a, 0x44, 0x63, 0xca, 0x85, 0x24, 0x63, 0xde, 0x2e,
	0x1a, 0x3a, 0x9a, 0xd4, 0xbb, 0x7f, 0x1e, 0x8d, 0x5f, 0xf2, 0x64, 0xa8, 0x90, 0x94, 0x73, 0x9c,
	0x71, 0xa1, 0xd2, 0xf0, 0xa4, 0x81, 0x7a, 0xa0, 0xb3, 0xd5, 0x2a, 0x27, 0x5c, 0x28, 0x35, 0xbc,
	0xd2, 0x2a, 0xd0, 0x9c, 0x71, 0x1c, 0x89, 0x19, 0x1a, 0x9e, 0x34, 0xac, 0x9f, 0x15, 0xe8, 0x3c,
	0x25, 0x38, 0xf3, 0xd7, 0x8b, 0x8c, 0x72, 0x92, 0x51, 0xfc, 0xff, 0x2e, 0xf0, 0xcd, 0x83, 0x0b,
	0xdc, 0xdf, 0x9a, 0xf5, 0x8b, 0x02, 0x86, 0x14, 0xe9, 0x91, 0xaf, 0x37, 0x24, 0xe7, 0xe8, 0x1d,
	0x68, 0xf8, 0xa5, 0x5e, 0xa1, 0xb4, 0xe5, 0xde, 0xdd, 0x9f, 0xf4, 0x7e, 0x4f, 0xde, 0x16, 0x8d,
	0xee, 0x83, 0x9e, 0x8a, 0x49, 0x8b, 0x4e, 0x5a, 0xee, 0x70, 0x3f, 0x6f, 0x6f, 0x0b, 0x5e, 0x09,
	0x45, 0x13, 0xa8, 0x71, 0x1c, 0xe6, 0xa2, 0xb9, 0x96, 0xdb, 0xbb, 0xb6, 0x54, 0xf1, 0x03, 0xf0,
	0x04, 0xc6, 0xda, 0x40, 0xab, 0xfc, 0x2b, 0x3c, 0xc6, 0x21, 0xd9, 0xa9, 0xa7, 0xdc, 0xbc, 0xde,
	0x3d, 0x68, 0x54, 0x88, 0xbe, 0x2a, 0x7e, 0x48, 0xaf, 0xee, 0xa7, 0x95, 0x15, 0xbc, 0x2d, 0xcc,
	0xfd, 0x55, 0x83, 0x46, 0xe9, 0xcd, 0xd1, 0x53, 0xd0, 0xe5, 0x00, 0xd0, 0xf0, 0xd0, 0x58, 0xca,
	0x29, 0x9a, 0x83, 0x83, 0xa4, 0x85, 0x6c, 0xeb, 0xe5, 0xef, 0xff, 0xb8, 0xf8, 0x51, 0x6d, 0xa1,
	0xe6, 0xf6, 0x5a, 0xa1, 0x8f, 0x41, 0x5f, 0x64, 0x04, 0x73, 0x82, 0x0e, 0x8b, 0x31, 0x0f, 0xbb,
	0xad, 0x3b, 0x82, 0xaa, 0x63, 0x5d, 0x52, 0xcd, 0x94, 0x09, 0xf2, 0x40, 0xfb, 0x90, 0x70, 0xf4,
	0xaf, 0x6b, 0xfb, 0x27, 0xc6, 0x9e, 0x60, 0xec, 0xa2, 0xce, 0x96, 0xd1, 0xf9, 0x96, 0x06, 0xdf,
	0xa1, 0x27, 0xa0, 0x7f, 0x96, 0x06, 0xb7, 0x57, 0x38, 0x10, 0x7c, 0xaf, 0x98, 0x57, 0xf8, 0x0a,
	0x99, 0x9f, 0x83, 0xfe, 0x3e, 0x89, 0x08, 0x27, 0xff, 0xa1, 0xb4, 0x67, 0xcb, 0xd3, 0x6c, 0x57,
	0x77, 0xdb, 0xfe, 0xa0, 0xb8, 0xdb, 0x95, 0xd4, 0xc9, 0x15, 0xea, 0xf9, 0x85, 0xf2, 0xc3, 0xc3,
	0x9f, 0x14, 0x94, 0x5c, 0x2e, 0xcd, 0xfa, 0x12, 0x3a, 0x1f, 0xb1, 0x75, 0x32, 0x9a, 0x93, 0x08,
	0xc7, 0x38, 0xa3, 0x3e, 0x72, 0xd7, 0x9c, 0xa7, 0xf9, 0xcc, 0x71, 0x6e, 0xfe, 0x89, 0x31, 0x5f,
	0x7b, 0xb1, 0xac, 0xf2, 0xdf, 0xab, 0xb0, 0x45, 0xa2, 0xab, 0xdd, 0xb3, 0xdf, 0x9e, 0xa8, 0x8a,
	0xea, 0x76, 0x71, 0x9a, 0x46, 0xd4, 0x17, 0xf7, 0xdc, 0x79, 0x91, 0xb3, 0x64, 0x76, 0xcd, 0x73,
	0x7e, 0x36, 0xd0, 0x58, 0x16, 0x7f, 0x71, 0xab, 0x6f, 0xdb, 0x72, 0xdb, 0xe2, 0x83, 0xea, 0xb1,
	0xd4, 0xc5, 0x38, 0xee, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xa3, 0xe0, 0xd7, 0x25, 0x07,
	0x00, 0x00,
}
