apiVersion: atlasdb.infoblox.com/v1alpha1
kind: DatabaseServer
metadata:
  name: contactsappdbserver
  namespace: contacts
spec:
  servicePort: 5432
  superUser: "postgres"
  superUserPassword: "postgres"
  postgres:
    image: postgres
---
apiVersion: atlasdb.infoblox.com/v1alpha1
kind: Database
metadata:
  name: contactsappdb
  namespace: contacts
spec:
  users:
  - name: atlasdbadmin
    password: Inf@blox
    role: admin
  - name: contacts
    password: contacts
    role: read
  serverType: postgres
  server: contactsappdbserver
---
apiVersion: atlasdb.infoblox.com/v1alpha1
kind: DatabaseSchema
metadata:
  name: contactsappschema
  namespace: contacts
spec:
  database: contactsappdb
  git: github://$GIT_USER:$GIT_TOKEN@infobloxopen/atlas-contacts-app/db/migrations
  version: 0002
