// Code generated by protoc-gen-go.
// source: pkg/pb/contacts.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pkg/pb/contacts.proto

It has these top-level messages:
	Profile
	CreateProfileRequest
	CreateProfileResponse
	ReadProfileRequest
	ReadProfileResponse
	UpdateProfileRequest
	UpdateProfileResponse
	DeleteProfileRequest
	ListProfileRequest
	ListProfilesResponse
	Group
	CreateGroupRequest
	CreateGroupResponse
	ReadGroupRequest
	ReadGroupResponse
	UpdateGroupRequest
	UpdateGroupResponse
	DeleteGroupRequest
	ListGroupRequest
	ListGroupsResponse
	Contact
	Email
	Address
	CreateContactRequest
	CreateContactResponse
	ReadContactRequest
	ReadContactResponse
	UpdateContactRequest
	UpdateContactResponse
	DeleteContactRequest
	ListContactsResponse
	SMSRequest
	ListContactRequest
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import google_protobuf1 "google.golang.org/genproto/protobuf/field_mask"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"
import gorm_types "github.com/infobloxopen/protoc-gen-gorm/types"
import infoblox_api "github.com/infobloxopen/atlas-app-toolkit/query"
import atlas_rpc "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Profile struct {
	Id       *atlas_rpc.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Notes    string                `protobuf:"bytes,3,opt,name=notes" json:"notes,omitempty"`
	Contacts []*Contact            `protobuf:"bytes,4,rep,name=contacts" json:"contacts,omitempty"`
	Groups   []*Group              `protobuf:"bytes,5,rep,name=groups" json:"groups,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Profile) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Profile) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *Profile) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type CreateProfileRequest struct {
	Payload *Profile `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *CreateProfileRequest) Reset()                    { *m = CreateProfileRequest{} }
func (m *CreateProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateProfileRequest) ProtoMessage()               {}
func (*CreateProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateProfileRequest) GetPayload() *Profile {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateProfileResponse struct {
	Result *Profile `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *CreateProfileResponse) Reset()                    { *m = CreateProfileResponse{} }
func (m *CreateProfileResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateProfileResponse) ProtoMessage()               {}
func (*CreateProfileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateProfileResponse) GetResult() *Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadProfileRequest struct {
	Id *atlas_rpc.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadProfileRequest) Reset()                    { *m = ReadProfileRequest{} }
func (m *ReadProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadProfileRequest) ProtoMessage()               {}
func (*ReadProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadProfileRequest) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadProfileResponse struct {
	Result *Profile `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ReadProfileResponse) Reset()                    { *m = ReadProfileResponse{} }
func (m *ReadProfileResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadProfileResponse) ProtoMessage()               {}
func (*ReadProfileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadProfileResponse) GetResult() *Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateProfileRequest struct {
	Payload *Profile `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *UpdateProfileRequest) Reset()                    { *m = UpdateProfileRequest{} }
func (m *UpdateProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProfileRequest) ProtoMessage()               {}
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateProfileRequest) GetPayload() *Profile {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateProfileResponse struct {
	Result *Profile `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *UpdateProfileResponse) Reset()                    { *m = UpdateProfileResponse{} }
func (m *UpdateProfileResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateProfileResponse) ProtoMessage()               {}
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateProfileResponse) GetResult() *Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteProfileRequest struct {
	Id *atlas_rpc.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteProfileRequest) Reset()                    { *m = DeleteProfileRequest{} }
func (m *DeleteProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteProfileRequest) ProtoMessage()               {}
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteProfileRequest) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ListProfileRequest struct {
	Filter  *infoblox_api.Filtering      `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	OrderBy *infoblox_api.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy" json:"order_by,omitempty"`
	Fields  *infoblox_api.FieldSelection `protobuf:"bytes,3,opt,name=fields" json:"fields,omitempty"`
	Paging  *infoblox_api.Pagination     `protobuf:"bytes,4,opt,name=paging" json:"paging,omitempty"`
}

func (m *ListProfileRequest) Reset()                    { *m = ListProfileRequest{} }
func (m *ListProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*ListProfileRequest) ProtoMessage()               {}
func (*ListProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListProfileRequest) GetFilter() *infoblox_api.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListProfileRequest) GetOrderBy() *infoblox_api.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListProfileRequest) GetFields() *infoblox_api.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListProfileRequest) GetPaging() *infoblox_api.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListProfilesResponse struct {
	Results []*Profile `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ListProfilesResponse) Reset()                    { *m = ListProfilesResponse{} }
func (m *ListProfilesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListProfilesResponse) ProtoMessage()               {}
func (*ListProfilesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ListProfilesResponse) GetResults() []*Profile {
	if m != nil {
		return m.Results
	}
	return nil
}

type Group struct {
	Id        *atlas_rpc.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name      string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Notes     string                `protobuf:"bytes,3,opt,name=notes" json:"notes,omitempty"`
	Profile   *Profile              `protobuf:"bytes,4,opt,name=profile" json:"profile,omitempty"`
	ProfileId *atlas_rpc.Identifier `protobuf:"bytes,5,opt,name=profile_id,json=profileId" json:"profile_id,omitempty"`
	Contacts  []*Contact            `protobuf:"bytes,6,rep,name=contacts" json:"contacts,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Group) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Group) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Group) GetProfileId() *atlas_rpc.Identifier {
	if m != nil {
		return m.ProfileId
	}
	return nil
}

func (m *Group) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type CreateGroupRequest struct {
	Payload *Group `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *CreateGroupRequest) Reset()                    { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()               {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateGroupRequest) GetPayload() *Group {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateGroupResponse struct {
	Result *Group `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *CreateGroupResponse) Reset()                    { *m = CreateGroupResponse{} }
func (m *CreateGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateGroupResponse) ProtoMessage()               {}
func (*CreateGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CreateGroupResponse) GetResult() *Group {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadGroupRequest struct {
	Id *atlas_rpc.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadGroupRequest) Reset()                    { *m = ReadGroupRequest{} }
func (m *ReadGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadGroupRequest) ProtoMessage()               {}
func (*ReadGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ReadGroupRequest) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadGroupResponse struct {
	Result *Group `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ReadGroupResponse) Reset()                    { *m = ReadGroupResponse{} }
func (m *ReadGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadGroupResponse) ProtoMessage()               {}
func (*ReadGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ReadGroupResponse) GetResult() *Group {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateGroupRequest struct {
	Payload *Group `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *UpdateGroupRequest) Reset()                    { *m = UpdateGroupRequest{} }
func (m *UpdateGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateGroupRequest) ProtoMessage()               {}
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UpdateGroupRequest) GetPayload() *Group {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateGroupResponse struct {
	Result *Group `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *UpdateGroupResponse) Reset()                    { *m = UpdateGroupResponse{} }
func (m *UpdateGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateGroupResponse) ProtoMessage()               {}
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *UpdateGroupResponse) GetResult() *Group {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteGroupRequest struct {
	Id *atlas_rpc.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteGroupRequest) Reset()                    { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()               {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *DeleteGroupRequest) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ListGroupRequest struct {
	Filter  *infoblox_api.Filtering      `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	OrderBy *infoblox_api.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy" json:"order_by,omitempty"`
	Fields  *infoblox_api.FieldSelection `protobuf:"bytes,3,opt,name=fields" json:"fields,omitempty"`
	Paging  *infoblox_api.Pagination     `protobuf:"bytes,4,opt,name=paging" json:"paging,omitempty"`
}

func (m *ListGroupRequest) Reset()                    { *m = ListGroupRequest{} }
func (m *ListGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*ListGroupRequest) ProtoMessage()               {}
func (*ListGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ListGroupRequest) GetFilter() *infoblox_api.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListGroupRequest) GetOrderBy() *infoblox_api.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListGroupRequest) GetFields() *infoblox_api.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListGroupRequest) GetPaging() *infoblox_api.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListGroupsResponse struct {
	Results []*Group `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ListGroupsResponse) Reset()                    { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()               {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ListGroupsResponse) GetResults() []*Group {
	if m != nil {
		return m.Results
	}
	return nil
}

type Contact struct {
	Id           *atlas_rpc.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FirstName    string                `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	MiddleName   string                `protobuf:"bytes,3,opt,name=middle_name,json=middleName" json:"middle_name,omitempty"`
	LastName     string                `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	PrimaryEmail string                `protobuf:"bytes,6,opt,name=primary_email,json=primaryEmail" json:"primary_email,omitempty"`
	Notes        string                `protobuf:"bytes,7,opt,name=notes" json:"notes,omitempty"`
	Emails       []*Email              `protobuf:"bytes,8,rep,name=emails" json:"emails,omitempty"`
	HomeAddress  *Address              `protobuf:"bytes,9,opt,name=home_address,json=homeAddress" json:"home_address,omitempty"`
	WorkAddress  *Address              `protobuf:"bytes,10,opt,name=work_address,json=workAddress" json:"work_address,omitempty"`
	ProfileId    *atlas_rpc.Identifier `protobuf:"bytes,11,opt,name=profile_id,json=profileId" json:"profile_id,omitempty"`
	Profile      *Profile              `protobuf:"bytes,12,opt,name=profile" json:"profile,omitempty"`
	Groups       []*Group              `protobuf:"bytes,13,rep,name=groups" json:"groups,omitempty"`
	// nicknames is arbitrary json, but should be used for a list of strings
	Nicknames *gorm_types.JSONValue `protobuf:"bytes,14,opt,name=nicknames" json:"nicknames,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *Contact) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Contact) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Contact) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Contact) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Contact) GetPrimaryEmail() string {
	if m != nil {
		return m.PrimaryEmail
	}
	return ""
}

func (m *Contact) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Contact) GetEmails() []*Email {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *Contact) GetHomeAddress() *Address {
	if m != nil {
		return m.HomeAddress
	}
	return nil
}

func (m *Contact) GetWorkAddress() *Address {
	if m != nil {
		return m.WorkAddress
	}
	return nil
}

func (m *Contact) GetProfileId() *atlas_rpc.Identifier {
	if m != nil {
		return m.ProfileId
	}
	return nil
}

func (m *Contact) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Contact) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Contact) GetNicknames() *gorm_types.JSONValue {
	if m != nil {
		return m.Nicknames
	}
	return nil
}

type Email struct {
	Id      uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Email) Reset()                    { *m = Email{} }
func (m *Email) String() string            { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()               {}
func (*Email) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *Email) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Email) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Address struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	City    string `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	State   string `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	Zip     string `protobuf:"bytes,4,opt,name=zip" json:"zip,omitempty"`
	Country string `protobuf:"bytes,5,opt,name=country" json:"country,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type CreateContactRequest struct {
	Payload *Contact `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *CreateContactRequest) Reset()                    { *m = CreateContactRequest{} }
func (m *CreateContactRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateContactRequest) ProtoMessage()               {}
func (*CreateContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *CreateContactRequest) GetPayload() *Contact {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateContactResponse struct {
	Result *Contact `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *CreateContactResponse) Reset()                    { *m = CreateContactResponse{} }
func (m *CreateContactResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateContactResponse) ProtoMessage()               {}
func (*CreateContactResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *CreateContactResponse) GetResult() *Contact {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadContactRequest struct {
	Id *atlas_rpc.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadContactRequest) Reset()                    { *m = ReadContactRequest{} }
func (m *ReadContactRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadContactRequest) ProtoMessage()               {}
func (*ReadContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ReadContactRequest) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadContactResponse struct {
	Result *Contact `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ReadContactResponse) Reset()                    { *m = ReadContactResponse{} }
func (m *ReadContactResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadContactResponse) ProtoMessage()               {}
func (*ReadContactResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ReadContactResponse) GetResult() *Contact {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateContactRequest struct {
	Payload    *Contact                    `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	UpdateMask *google_protobuf1.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
}

func (m *UpdateContactRequest) Reset()                    { *m = UpdateContactRequest{} }
func (m *UpdateContactRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateContactRequest) ProtoMessage()               {}
func (*UpdateContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *UpdateContactRequest) GetPayload() *Contact {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateContactRequest) GetUpdateMask() *google_protobuf1.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type UpdateContactResponse struct {
	Result *Contact `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *UpdateContactResponse) Reset()                    { *m = UpdateContactResponse{} }
func (m *UpdateContactResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateContactResponse) ProtoMessage()               {}
func (*UpdateContactResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *UpdateContactResponse) GetResult() *Contact {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteContactRequest struct {
	Id *atlas_rpc.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteContactRequest) Reset()                    { *m = DeleteContactRequest{} }
func (m *DeleteContactRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteContactRequest) ProtoMessage()               {}
func (*DeleteContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *DeleteContactRequest) GetId() *atlas_rpc.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ListContactsResponse struct {
	Results []*Contact `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ListContactsResponse) Reset()                    { *m = ListContactsResponse{} }
func (m *ListContactsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListContactsResponse) ProtoMessage()               {}
func (*ListContactsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ListContactsResponse) GetResults() []*Contact {
	if m != nil {
		return m.Results
	}
	return nil
}

type SMSRequest struct {
	Id      uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *SMSRequest) Reset()                    { *m = SMSRequest{} }
func (m *SMSRequest) String() string            { return proto.CompactTextString(m) }
func (*SMSRequest) ProtoMessage()               {}
func (*SMSRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *SMSRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SMSRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ListContactRequest struct {
	Filter  *infoblox_api.Filtering      `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	OrderBy *infoblox_api.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy" json:"order_by,omitempty"`
	Fields  *infoblox_api.FieldSelection `protobuf:"bytes,3,opt,name=fields" json:"fields,omitempty"`
	Paging  *infoblox_api.Pagination     `protobuf:"bytes,4,opt,name=paging" json:"paging,omitempty"`
}

func (m *ListContactRequest) Reset()                    { *m = ListContactRequest{} }
func (m *ListContactRequest) String() string            { return proto.CompactTextString(m) }
func (*ListContactRequest) ProtoMessage()               {}
func (*ListContactRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *ListContactRequest) GetFilter() *infoblox_api.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListContactRequest) GetOrderBy() *infoblox_api.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListContactRequest) GetFields() *infoblox_api.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListContactRequest) GetPaging() *infoblox_api.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

func init() {
	proto.RegisterType((*Profile)(nil), "api.contacts.Profile")
	proto.RegisterType((*CreateProfileRequest)(nil), "api.contacts.CreateProfileRequest")
	proto.RegisterType((*CreateProfileResponse)(nil), "api.contacts.CreateProfileResponse")
	proto.RegisterType((*ReadProfileRequest)(nil), "api.contacts.ReadProfileRequest")
	proto.RegisterType((*ReadProfileResponse)(nil), "api.contacts.ReadProfileResponse")
	proto.RegisterType((*UpdateProfileRequest)(nil), "api.contacts.UpdateProfileRequest")
	proto.RegisterType((*UpdateProfileResponse)(nil), "api.contacts.UpdateProfileResponse")
	proto.RegisterType((*DeleteProfileRequest)(nil), "api.contacts.DeleteProfileRequest")
	proto.RegisterType((*ListProfileRequest)(nil), "api.contacts.ListProfileRequest")
	proto.RegisterType((*ListProfilesResponse)(nil), "api.contacts.ListProfilesResponse")
	proto.RegisterType((*Group)(nil), "api.contacts.Group")
	proto.RegisterType((*CreateGroupRequest)(nil), "api.contacts.CreateGroupRequest")
	proto.RegisterType((*CreateGroupResponse)(nil), "api.contacts.CreateGroupResponse")
	proto.RegisterType((*ReadGroupRequest)(nil), "api.contacts.ReadGroupRequest")
	proto.RegisterType((*ReadGroupResponse)(nil), "api.contacts.ReadGroupResponse")
	proto.RegisterType((*UpdateGroupRequest)(nil), "api.contacts.UpdateGroupRequest")
	proto.RegisterType((*UpdateGroupResponse)(nil), "api.contacts.UpdateGroupResponse")
	proto.RegisterType((*DeleteGroupRequest)(nil), "api.contacts.DeleteGroupRequest")
	proto.RegisterType((*ListGroupRequest)(nil), "api.contacts.ListGroupRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "api.contacts.ListGroupsResponse")
	proto.RegisterType((*Contact)(nil), "api.contacts.Contact")
	proto.RegisterType((*Email)(nil), "api.contacts.Email")
	proto.RegisterType((*Address)(nil), "api.contacts.Address")
	proto.RegisterType((*CreateContactRequest)(nil), "api.contacts.CreateContactRequest")
	proto.RegisterType((*CreateContactResponse)(nil), "api.contacts.CreateContactResponse")
	proto.RegisterType((*ReadContactRequest)(nil), "api.contacts.ReadContactRequest")
	proto.RegisterType((*ReadContactResponse)(nil), "api.contacts.ReadContactResponse")
	proto.RegisterType((*UpdateContactRequest)(nil), "api.contacts.UpdateContactRequest")
	proto.RegisterType((*UpdateContactResponse)(nil), "api.contacts.UpdateContactResponse")
	proto.RegisterType((*DeleteContactRequest)(nil), "api.contacts.DeleteContactRequest")
	proto.RegisterType((*ListContactsResponse)(nil), "api.contacts.ListContactsResponse")
	proto.RegisterType((*SMSRequest)(nil), "api.contacts.SMSRequest")
	proto.RegisterType((*ListContactRequest)(nil), "api.contacts.ListContactRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Profiles service

type ProfilesClient interface {
	Create(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error)
	Read(ctx context.Context, in *ReadProfileRequest, opts ...grpc.CallOption) (*ReadProfileResponse, error)
	Update(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	Delete(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	List(ctx context.Context, in *ListProfileRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
}

type profilesClient struct {
	cc *grpc.ClientConn
}

func NewProfilesClient(cc *grpc.ClientConn) ProfilesClient {
	return &profilesClient{cc}
}

func (c *profilesClient) Create(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error) {
	out := new(CreateProfileResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Profiles/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) Read(ctx context.Context, in *ReadProfileRequest, opts ...grpc.CallOption) (*ReadProfileResponse, error) {
	out := new(ReadProfileResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Profiles/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) Update(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	out := new(UpdateProfileResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Profiles/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) Delete(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/api.contacts.Profiles/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) List(ctx context.Context, in *ListProfileRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	out := new(ListProfilesResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Profiles/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Profiles service

type ProfilesServer interface {
	Create(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error)
	Read(context.Context, *ReadProfileRequest) (*ReadProfileResponse, error)
	Update(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	Delete(context.Context, *DeleteProfileRequest) (*google_protobuf.Empty, error)
	List(context.Context, *ListProfileRequest) (*ListProfilesResponse, error)
}

func RegisterProfilesServer(s *grpc.Server, srv ProfilesServer) {
	s.RegisterService(&_Profiles_serviceDesc, srv)
}

func _Profiles_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Profiles/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).Create(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Profiles/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).Read(ctx, req.(*ReadProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Profiles/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).Update(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Profiles/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).Delete(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Profiles/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).List(ctx, req.(*ListProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profiles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.contacts.Profiles",
	HandlerType: (*ProfilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Profiles_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Profiles_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Profiles_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Profiles_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Profiles_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/contacts.proto",
}

// Client API for Groups service

type GroupsClient interface {
	Create(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	Read(ctx context.Context, in *ReadGroupRequest, opts ...grpc.CallOption) (*ReadGroupResponse, error)
	Update(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error)
	Delete(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	List(ctx context.Context, in *ListGroupRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
}

type groupsClient struct {
	cc *grpc.ClientConn
}

func NewGroupsClient(cc *grpc.ClientConn) GroupsClient {
	return &groupsClient{cc}
}

func (c *groupsClient) Create(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	out := new(CreateGroupResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Groups/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Read(ctx context.Context, in *ReadGroupRequest, opts ...grpc.CallOption) (*ReadGroupResponse, error) {
	out := new(ReadGroupResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Groups/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Update(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error) {
	out := new(UpdateGroupResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Groups/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Delete(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/api.contacts.Groups/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) List(ctx context.Context, in *ListGroupRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Groups/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Groups service

type GroupsServer interface {
	Create(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	Read(context.Context, *ReadGroupRequest) (*ReadGroupResponse, error)
	Update(context.Context, *UpdateGroupRequest) (*UpdateGroupResponse, error)
	Delete(context.Context, *DeleteGroupRequest) (*google_protobuf.Empty, error)
	List(context.Context, *ListGroupRequest) (*ListGroupsResponse, error)
}

func RegisterGroupsServer(s *grpc.Server, srv GroupsServer) {
	s.RegisterService(&_Groups_serviceDesc, srv)
}

func _Groups_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Groups/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Create(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Groups/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Read(ctx, req.(*ReadGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Groups/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Update(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Groups/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Delete(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Groups/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).List(ctx, req.(*ListGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Groups_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.contacts.Groups",
	HandlerType: (*GroupsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Groups_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Groups_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Groups_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Groups_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Groups_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/contacts.proto",
}

// Client API for Contacts service

type ContactsClient interface {
	Create(ctx context.Context, in *CreateContactRequest, opts ...grpc.CallOption) (*CreateContactResponse, error)
	Read(ctx context.Context, in *ReadContactRequest, opts ...grpc.CallOption) (*ReadContactResponse, error)
	Update(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error)
	Delete(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	List(ctx context.Context, in *ListContactRequest, opts ...grpc.CallOption) (*ListContactsResponse, error)
	SendSMS(ctx context.Context, in *SMSRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type contactsClient struct {
	cc *grpc.ClientConn
}

func NewContactsClient(cc *grpc.ClientConn) ContactsClient {
	return &contactsClient{cc}
}

func (c *contactsClient) Create(ctx context.Context, in *CreateContactRequest, opts ...grpc.CallOption) (*CreateContactResponse, error) {
	out := new(CreateContactResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Read(ctx context.Context, in *ReadContactRequest, opts ...grpc.CallOption) (*ReadContactResponse, error) {
	out := new(ReadContactResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Update(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error) {
	out := new(UpdateContactResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Delete(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) List(ctx context.Context, in *ListContactRequest, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	out := new(ListContactsResponse)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) SendSMS(ctx context.Context, in *SMSRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/api.contacts.Contacts/SendSMS", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Contacts service

type ContactsServer interface {
	Create(context.Context, *CreateContactRequest) (*CreateContactResponse, error)
	Read(context.Context, *ReadContactRequest) (*ReadContactResponse, error)
	Update(context.Context, *UpdateContactRequest) (*UpdateContactResponse, error)
	Delete(context.Context, *DeleteContactRequest) (*google_protobuf.Empty, error)
	List(context.Context, *ListContactRequest) (*ListContactsResponse, error)
	SendSMS(context.Context, *SMSRequest) (*google_protobuf.Empty, error)
}

func RegisterContactsServer(s *grpc.Server, srv ContactsServer) {
	s.RegisterService(&_Contacts_serviceDesc, srv)
}

func _Contacts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Create(ctx, req.(*CreateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Read(ctx, req.(*ReadContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Update(ctx, req.(*UpdateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Delete(ctx, req.(*DeleteContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).List(ctx, req.(*ListContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_SendSMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).SendSMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/SendSMS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).SendSMS(ctx, req.(*SMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Contacts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.contacts.Contacts",
	HandlerType: (*ContactsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Contacts_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Contacts_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Contacts_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Contacts_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Contacts_List_Handler,
		},
		{
			MethodName: "SendSMS",
			Handler:    _Contacts_SendSMS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/contacts.proto",
}

func init() { proto.RegisterFile("pkg/pb/contacts.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1735 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x59, 0x4f, 0x6f, 0xe3, 0xc6,
	0x15, 0x0f, 0x65, 0x59, 0x7f, 0x9e, 0x1d, 0xc7, 0x3b, 0xeb, 0xcd, 0xd2, 0x8a, 0x93, 0x28, 0x2c,
	0x0a, 0x2c, 0xec, 0x4a, 0xf4, 0x6a, 0x8d, 0xa6, 0x6b, 0xa3, 0x40, 0x22, 0x67, 0xb3, 0xc8, 0xa2,
	0x9b, 0x06, 0x12, 0x5a, 0xa0, 0x01, 0x0a, 0x75, 0x24, 0x8e, 0xe4, 0x89, 0x29, 0x0e, 0xc3, 0xa1,
	0x9a, 0xaa, 0x45, 0x80, 0xa2, 0x2d, 0xfa, 0x01, 0xda, 0x4b, 0x4f, 0xfd, 0x0a, 0x3d, 0xf4, 0x64,
	0x9d, 0xfa, 0x19, 0xba, 0x40, 0x6f, 0x45, 0x2f, 0xbd, 0xf4, 0x53, 0xb4, 0xe0, 0xfc, 0xa1, 0x48,
	0x8a, 0x92, 0xb5, 0x76, 0x91, 0xc3, 0x5e, 0x0c, 0x92, 0xf3, 0x7b, 0x7f, 0xe7, 0xbd, 0xdf, 0xbc,
	0x91, 0xe1, 0x9e, 0x7f, 0x39, 0xb2, 0xfd, 0xbe, 0x3d, 0x60, 0x5e, 0x88, 0x07, 0x21, 0x6f, 0xfa,
	0x01, 0x0b, 0x19, 0xda, 0xc6, 0x3e, 0x6d, 0xea, 0x6f, 0xb5, 0xb7, 0x46, 0x8c, 0x8d, 0x5c, 0x62,
	0x8b, 0xb5, 0xfe, 0x64, 0x68, 0x93, 0xb1, 0x1f, 0x4e, 0x25, 0xb4, 0x56, 0xcf, 0x2e, 0x0e, 0x29,
	0x71, 0x9d, 0xde, 0x18, 0xf3, 0x4b, 0x85, 0x38, 0x50, 0x08, 0xec, 0x53, 0x1b, 0x7b, 0x1e, 0x0b,
	0x71, 0x48, 0x99, 0xa7, 0x4c, 0xd5, 0xce, 0x46, 0x34, 0xbc, 0x98, 0xf4, 0x9b, 0x03, 0x36, 0xb6,
	0xdd, 0xe9, 0x30, 0x94, 0x8a, 0x06, 0x8d, 0x11, 0xf1, 0x1a, 0x3f, 0xc7, 0x2e, 0x75, 0x70, 0x48,
	0xec, 0x85, 0x07, 0x25, 0xfc, 0x9d, 0x04, 0x98, 0x7f, 0x85, 0x47, 0x23, 0x12, 0xd8, 0xcc, 0x17,
	0xea, 0x73, 0x4c, 0x9d, 0x26, 0x4c, 0x51, 0x6f, 0xc8, 0xfa, 0x2e, 0xfb, 0x05, 0xf3, 0x89, 0x97,
	0x34, 0x39, 0x62, 0xc1, 0x38, 0x56, 0x11, 0xbd, 0x28, 0xd9, 0xc7, 0xeb, 0xca, 0x86, 0x53, 0x9f,
	0x70, 0xf9, 0x57, 0x89, 0x3e, 0x5b, 0x26, 0x8a, 0x43, 0x17, 0xf3, 0x06, 0xf6, 0xfd, 0x46, 0xc8,
	0x98, 0x7b, 0x49, 0x43, 0xfb, 0xcb, 0x09, 0x09, 0xa6, 0xf6, 0x80, 0xb9, 0x2e, 0x19, 0x44, 0x2e,
	0xf4, 0x98, 0x4f, 0x02, 0x1c, 0xb2, 0x40, 0xeb, 0x7a, 0xb2, 0xbe, 0xae, 0xc0, 0x1f, 0xd8, 0x01,
	0xe1, 0x6c, 0x12, 0x0c, 0x48, 0xfc, 0x20, 0xd5, 0x58, 0xff, 0x30, 0xa0, 0xfc, 0x59, 0xc0, 0x86,
	0xd4, 0x25, 0xe8, 0x7d, 0x28, 0x50, 0xc7, 0x34, 0xea, 0xc6, 0x83, 0xad, 0xd6, 0xbd, 0xa6, 0xd0,
	0xd3, 0x0c, 0xfc, 0x41, 0xf3, 0x13, 0x87, 0x78, 0x21, 0x1d, 0x52, 0x12, 0xb4, 0x77, 0x67, 0x57,
	0xfb, 0xdb, 0x00, 0xa8, 0xc4, 0x49, 0x40, 0xb1, 0xfb, 0xc0, 0xe8, 0x14, 0xa8, 0x83, 0x10, 0x14,
	0x3d, 0x3c, 0x26, 0x66, 0xa1, 0x6e, 0x3c, 0xa8, 0x76, 0xc4, 0x33, 0xda, 0x83, 0x4d, 0x8f, 0x85,
	0x84, 0x9b, 0x1b, 0xe2, 0xa3, 0x7c, 0x41, 0x0f, 0xa1, 0xa2, 0x8b, 0xc9, 0x2c, 0xd6, 0x37, 0xa4,
	0xa1, 0x44, 0x85, 0x35, 0xcf, 0xe5, 0x43, 0x27, 0x86, 0xa1, 0x23, 0x28, 0x8d, 0x02, 0x36, 0xf1,
	0xb9, 0xb9, 0x29, 0x04, 0xee, 0xa6, 0x05, 0x9e, 0x46, 0x6b, 0x1d, 0x05, 0x39, 0xad, 0xcc, 0xae,
	0xf6, 0x8b, 0x15, 0xa3, 0x6e, 0x58, 0x4f, 0x61, 0xef, 0x3c, 0x20, 0x38, 0x24, 0x2a, 0xba, 0x0e,
	0xf9, 0x72, 0x42, 0x78, 0x88, 0x6c, 0x28, 0xfb, 0x78, 0xea, 0x32, 0x9c, 0x88, 0x34, 0xa9, 0x4f,
	0xc3, 0x35, 0xca, 0xfa, 0x18, 0xee, 0x65, 0x14, 0x71, 0x9f, 0x79, 0x9c, 0xa0, 0x06, 0x94, 0x02,
	0xc2, 0x27, 0x6e, 0xb8, 0x5a, 0x91, 0x02, 0x59, 0x67, 0x80, 0x3a, 0x04, 0x3b, 0x19, 0x77, 0xbe,
	0x7d, 0x6d, 0xce, 0xa3, 0x0c, 0x5b, 0x1f, 0xc1, 0xdd, 0x94, 0xf0, 0xcd, 0x5c, 0x78, 0x0a, 0x7b,
	0x3f, 0xf2, 0x9d, 0xff, 0x4f, 0x4e, 0x32, 0x8a, 0x6e, 0xe6, 0xd0, 0xf7, 0x61, 0xef, 0x23, 0xe2,
	0x92, 0x05, 0x87, 0xd6, 0xcc, 0xca, 0xbf, 0x0c, 0x40, 0x3f, 0xa0, 0x3c, 0x5c, 0x08, 0xa7, 0x34,
	0xa4, 0x6e, 0x48, 0x02, 0xa5, 0xe1, 0x7e, 0x53, 0x37, 0x88, 0xf0, 0xe6, 0x63, 0xb1, 0x46, 0xbd,
	0x51, 0x47, 0xc1, 0xd0, 0x31, 0x54, 0x58, 0xe0, 0x90, 0xa0, 0xd7, 0x9f, 0x8a, 0x1a, 0x8e, 0x8c,
	0xa6, 0x44, 0xba, 0x2c, 0x08, 0x23, 0x81, 0xb2, 0x80, 0xb5, 0xa7, 0xe8, 0x24, 0x32, 0x41, 0x5c,
	0x47, 0x96, 0xf7, 0x56, 0xeb, 0x20, 0x6b, 0x82, 0xb8, 0x4e, 0x97, 0xa8, 0xde, 0xed, 0x28, 0x2c,
	0x3a, 0x86, 0x92, 0x8f, 0x47, 0xd4, 0x1b, 0x99, 0x45, 0x21, 0x65, 0xa6, 0xa5, 0x3e, 0x8b, 0xd6,
	0xb0, 0x94, 0x90, 0xb8, 0x68, 0xc7, 0x12, 0x01, 0xf2, 0x38, 0xcf, 0x36, 0x94, 0x65, 0x0a, 0xb9,
	0x69, 0xe4, 0xb5, 0x51, 0xbc, 0x63, 0x0a, 0x65, 0xfd, 0xb9, 0x00, 0x9b, 0xa2, 0x55, 0xbe, 0x89,
	0x2e, 0x7f, 0x1f, 0xca, 0xbe, 0x74, 0x40, 0x05, 0x9a, 0xef, 0x5d, 0xbb, 0x34, 0xbb, 0xda, 0x2f,
	0x58, 0xaf, 0x75, 0x34, 0x1a, 0x9d, 0x00, 0xa8, 0xc7, 0x1e, 0x75, 0xcc, 0xcd, 0x55, 0xfb, 0x5f,
	0x55, 0xc0, 0x4f, 0x1c, 0xf4, 0x38, 0x41, 0x2a, 0xa5, 0x15, 0xa4, 0x22, 0xed, 0xb5, 0x5e, 0x9b,
	0x93, 0x4b, 0x82, 0x2f, 0xce, 0x01, 0xc9, 0x36, 0x97, 0x84, 0xa2, 0x4a, 0xa9, 0x91, 0xed, 0x8c,
	0x5c, 0xf6, 0x89, 0xfb, 0xa2, 0x0d, 0x77, 0x53, 0x4a, 0xd4, 0x6e, 0x1d, 0x65, 0xba, 0x22, 0x9f,
	0xc2, 0x54, 0x4f, 0x3c, 0x86, 0xdd, 0xa8, 0xd5, 0x53, 0x6e, 0xac, 0xd9, 0x0f, 0x1f, 0xc0, 0x9d,
	0x84, 0xe8, 0x4d, 0x8c, 0x9f, 0x03, 0x92, 0x8d, 0x7d, 0xcb, 0x2c, 0xa4, 0x94, 0xdc, 0xc4, 0x91,
	0x33, 0x40, 0x92, 0x19, 0x6e, 0x92, 0x87, 0x7f, 0x1a, 0xb0, 0x1b, 0xb5, 0x4d, 0x4a, 0xf6, 0x15,
	0x62, 0x85, 0x73, 0x49, 0x7b, 0x22, 0x3c, 0x9e, 0xe0, 0xde, 0x0c, 0x27, 0xe4, 0xef, 0x92, 0x66,
	0x84, 0xff, 0x16, 0xa1, 0xac, 0x1a, 0xe3, 0xe6, 0x9c, 0xf0, 0x36, 0xc0, 0x90, 0x06, 0x3c, 0xec,
	0x25, 0x98, 0xa1, 0x2a, 0xbe, 0x7c, 0x1a, 0xd1, 0xc3, 0xbb, 0xb0, 0x35, 0xa6, 0x8e, 0xe3, 0x12,
	0xb9, 0x2e, 0x49, 0x02, 0xe4, 0x27, 0x01, 0x78, 0x0b, 0xaa, 0x2e, 0xd6, 0xe2, 0x45, 0xb1, 0x5c,
	0x89, 0x3e, 0x88, 0xc5, 0x13, 0x78, 0xdd, 0x0f, 0xe8, 0x18, 0x07, 0xd3, 0x1e, 0x19, 0x63, 0xea,
	0x9a, 0xa5, 0x08, 0xd0, 0x7e, 0x23, 0xea, 0xe2, 0x5d, 0x63, 0xf6, 0x9f, 0xbf, 0x6d, 0x14, 0x83,
	0xc2, 0xcf, 0x8c, 0xce, 0xb6, 0x42, 0x3d, 0x89, 0x40, 0x73, 0x4a, 0x2a, 0x27, 0x29, 0xe9, 0x08,
	0x4a, 0x42, 0x07, 0x37, 0x2b, 0x79, 0xb9, 0x11, 0xa2, 0x1d, 0x05, 0x41, 0xdf, 0x83, 0xed, 0x0b,
	0x36, 0x26, 0x3d, 0xec, 0x38, 0x01, 0xe1, 0xdc, 0xac, 0xe6, 0x91, 0xd8, 0x87, 0x72, 0xb1, 0xb3,
	0x15, 0x41, 0xd5, 0x4b, 0x24, 0xf9, 0x15, 0x0b, 0x2e, 0x63, 0x49, 0x58, 0x29, 0x19, 0x41, 0xb5,
	0x64, 0x9a, 0xfa, 0xb6, 0xd6, 0xa4, 0xbe, 0x04, 0xd3, 0x6e, 0xbf, 0x14, 0xd3, 0x9e, 0xc7, 0x53,
	0xd5, 0xeb, 0x4b, 0x6b, 0xa5, 0xfd, 0xe6, 0xec, 0x6a, 0x1f, 0xb5, 0x76, 0x61, 0x47, 0x40, 0x7b,
	0x7a, 0x55, 0x4f, 0x5b, 0xe8, 0x11, 0x54, 0x3d, 0x3a, 0xb8, 0x8c, 0x36, 0x8f, 0x9b, 0x3b, 0xca,
	0xbe, 0x18, 0x95, 0xe5, 0xd4, 0xfb, 0xac, 0xfb, 0xc3, 0x4f, 0x7f, 0x8c, 0xdd, 0x09, 0xe9, 0xcc,
	0x71, 0x09, 0xca, 0xed, 0xc3, 0xa6, 0xdc, 0xb2, 0x9d, 0xb8, 0xfc, 0x8a, 0xa2, 0xaa, 0x8e, 0xa0,
	0xac, 0x13, 0x28, 0x4a, 0xaa, 0x7d, 0x27, 0x92, 0x81, 0xc2, 0x71, 0x62, 0xd3, 0x35, 0xe2, 0xf4,
	0x60, 0x76, 0xb5, 0x6f, 0x56, 0x8c, 0xe8, 0x78, 0xea, 0x33, 0xe6, 0x22, 0xa0, 0xbc, 0xa7, 0x0a,
	0xa2, 0x6e, 0x58, 0xbf, 0x35, 0xa0, 0xac, 0x53, 0x6c, 0xce, 0xd5, 0x1a, 0xa2, 0x36, 0xf4, 0x6b,
	0x24, 0x3b, 0xa0, 0xe1, 0x54, 0x1f, 0x6d, 0xd1, 0x73, 0x54, 0x47, 0x3c, 0xc4, 0xa1, 0xae, 0x5a,
	0xf9, 0x82, 0x76, 0x61, 0xe3, 0x97, 0xd4, 0x57, 0xa5, 0x1a, 0x3d, 0x46, 0x5a, 0x07, 0x6c, 0xe2,
	0x85, 0xc1, 0x54, 0x1c, 0x58, 0xd5, 0x8e, 0x7e, 0xcd, 0x1b, 0x46, 0xf5, 0x78, 0xbb, 0xe6, 0xe0,
	0xa5, 0xe1, 0x8b, 0xc3, 0x68, 0xac, 0x68, 0xbd, 0xc1, 0x4b, 0xc3, 0x33, 0xc3, 0x68, 0xc6, 0x9d,
	0x97, 0x1b, 0x46, 0x6f, 0xe9, 0xc2, 0xef, 0x0c, 0x3d, 0x8d, 0xde, 0x32, 0x29, 0xe8, 0x0c, 0xb6,
	0x26, 0x42, 0x91, 0xb8, 0x6b, 0x2a, 0xae, 0xae, 0x35, 0xe5, 0x65, 0xb3, 0xa9, 0xaf, 0xa3, 0x92,
	0x7e, 0x9f, 0x63, 0x7e, 0xd9, 0x01, 0x09, 0x8f, 0x9e, 0xe7, 0xa3, 0xec, 0x2d, 0xc3, 0x89, 0x47,
	0xd9, 0x9b, 0xe5, 0x54, 0x0d, 0x7a, 0xe7, 0xba, 0xc5, 0xd6, 0x1d, 0xf4, 0xe2, 0x64, 0x68, 0x5a,
	0xff, 0x2e, 0x40, 0xf7, 0x79, 0x57, 0x5b, 0xcf, 0x76, 0x96, 0x09, 0xe5, 0x31, 0xe1, 0x1c, 0x8f,
	0x34, 0x59, 0xeb, 0xd7, 0x78, 0x96, 0x5e, 0xd8, 0x8c, 0x57, 0xe5, 0xd4, 0x6c, 0xbd, 0x28, 0x42,
	0x45, 0x0f, 0xd2, 0x68, 0x0c, 0x25, 0xd9, 0x48, 0xc8, 0xca, 0x24, 0x34, 0xe7, 0xd2, 0x58, 0xfb,
	0xd6, 0x4a, 0x8c, 0xdc, 0x2a, 0xab, 0xf6, 0x9b, 0x17, 0xff, 0xfe, 0x63, 0x61, 0xcf, 0xaa, 0xda,
	0x8a, 0x64, 0xf9, 0x69, 0x5c, 0xa2, 0x0c, 0x8a, 0x51, 0xcb, 0xa0, 0x7a, 0x5a, 0xd1, 0xe2, 0x85,
	0xb0, 0xf6, 0xde, 0x0a, 0x84, 0x32, 0x64, 0x09, 0x43, 0x07, 0xa8, 0x16, 0x1b, 0xb2, 0x7f, 0x45,
	0x9d, 0xa6, 0xbe, 0xd9, 0xf7, 0xa8, 0xf3, 0x35, 0xfa, 0xbd, 0x01, 0x25, 0x59, 0xd7, 0xd9, 0x00,
	0xf3, 0x6e, 0x80, 0xd9, 0x00, 0x73, 0x2f, 0x77, 0xd6, 0x23, 0x61, 0xb7, 0x51, 0xb3, 0x12, 0x76,
	0x55, 0x80, 0xcd, 0x8c, 0xfd, 0x79, 0xe4, 0x13, 0x28, 0xc9, 0xbe, 0xc8, 0xfa, 0x91, 0x77, 0xf1,
	0xab, 0xbd, 0xb9, 0xd0, 0xb5, 0x4f, 0xc6, 0x7e, 0x38, 0xb5, 0xec, 0xd9, 0xd5, 0x7e, 0x35, 0xfe,
	0xa5, 0x42, 0xc6, 0x7f, 0xb8, 0x2a, 0xfe, 0x1e, 0x14, 0xa3, 0x6a, 0xce, 0x26, 0x7c, 0xf1, 0xb6,
	0x58, 0xb3, 0x96, 0x22, 0xe2, 0x2e, 0xb4, 0xee, 0x08, 0x8b, 0x5b, 0x68, 0xbe, 0xb5, 0x35, 0x71,
	0xa2, 0x56, 0x8c, 0xd6, 0x5f, 0x8b, 0x50, 0x92, 0x83, 0x18, 0x1a, 0xc5, 0x35, 0x55, 0xcf, 0xab,
	0x97, 0xe4, 0x34, 0x9a, 0xdd, 0xe6, 0x9c, 0x5b, 0x83, 0x65, 0x0a, 0xa3, 0xc8, 0x2a, 0xdb, 0xea,
	0xc7, 0x8d, 0x38, 0xa7, 0x54, 0x55, 0xd3, 0x3b, 0x8b, 0xb5, 0x92, 0x32, 0xf2, 0xee, 0xd2, 0x75,
	0x65, 0xa2, 0x2e, 0x4c, 0xd4, 0x90, 0xa9, 0x4c, 0x2c, 0xe6, 0xf1, 0xd7, 0xf3, 0x3a, 0xaa, 0xe7,
	0xd5, 0xc8, 0xaa, 0xa0, 0x72, 0x2e, 0x01, 0xd6, 0x43, 0x61, 0xf1, 0xa8, 0x56, 0x8f, 0x2d, 0x5e,
	0x5b, 0x41, 0x2c, 0xae, 0xa0, 0x7a, 0x5e, 0x05, 0xa5, 0x3c, 0x58, 0x56, 0x3f, 0x47, 0xb3, 0xab,
	0xfd, 0xb2, 0xba, 0x01, 0xcb, 0x98, 0x0f, 0x97, 0xc7, 0xfc, 0x13, 0x55, 0x3b, 0xef, 0x2c, 0x56,
	0x46, 0xca, 0x58, 0x7d, 0xc9, 0xfa, 0xbc, 0x6e, 0xde, 0x10, 0xb6, 0xaa, 0x48, 0x6f, 0x61, 0x5c,
	0x35, 0x7f, 0xd9, 0x84, 0x8a, 0xe6, 0xfa, 0xeb, 0xb8, 0x28, 0xcd, 0xc8, 0xf9, 0x5c, 0x94, 0x39,
	0xbc, 0x12, 0x5c, 0x14, 0x5f, 0x75, 0xd7, 0xe1, 0xa2, 0x8c, 0xa9, 0xf7, 0x56, 0x20, 0x16, 0xb8,
	0x48, 0xc3, 0x5e, 0x9e, 0x8b, 0x56, 0x07, 0x98, 0x7b, 0x3a, 0x27, 0xb8, 0x68, 0x6e, 0xf7, 0xb6,
	0x5c, 0x94, 0xf1, 0xe3, 0x1a, 0x2e, 0x52, 0xe8, 0x98, 0x8b, 0x96, 0xc7, 0xbf, 0x82, 0x8b, 0x32,
	0x26, 0xad, 0xa5, 0x88, 0x3c, 0x2e, 0x8a, 0x7f, 0x22, 0xfd, 0x1c, 0xca, 0x5d, 0xe2, 0x39, 0xdd,
	0xe7, 0x5d, 0x64, 0xa6, 0x35, 0xcc, 0x47, 0x81, 0xa5, 0xe1, 0xbc, 0x2d, 0xf4, 0xdd, 0xb7, 0x50,
	0x2a, 0x82, 0xaf, 0x6d, 0x3e, 0xe6, 0xa7, 0xc6, 0xa1, 0xae, 0xd8, 0xf6, 0xdf, 0x8d, 0x3f, 0x7c,
	0xf8, 0x27, 0x03, 0x79, 0xf3, 0xba, 0xb5, 0x7e, 0x0a, 0x3b, 0xcf, 0xd8, 0x85, 0x57, 0x6f, 0x13,
	0x17, 0x8f, 0x71, 0x40, 0x07, 0xa8, 0x75, 0x11, 0x86, 0x3e, 0x3f, 0xb5, 0xed, 0xd5, 0x3f, 0x4e,
	0x6b, 0x43, 0x0d, 0xec, 0xfb, 0xb5, 0xfb, 0x5f, 0xf4, 0xb5, 0xfc, 0x07, 0xf1, 0x11, 0x3e, 0x60,
	0xe3, 0xd6, 0xc6, 0xc3, 0xe6, 0xf1, 0x61, 0xc1, 0x28, 0xb4, 0x76, 0xb1, 0xef, 0xbb, 0x74, 0x20,
	0x4e, 0x73, 0xfb, 0x0b, 0xce, 0xbc, 0xd3, 0x85, 0x2f, 0x9f, 0x9f, 0xac, 0x6f, 0xd1, 0x96, 0xff,
	0xe9, 0x38, 0xf3, 0xfb, 0xfd, 0x92, 0xc8, 0xc5, 0xa3, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x7c,
	0xb2, 0x66, 0x0a, 0xfd, 0x18, 0x00, 0x00,
}
