// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/pb/contacts.proto

package pb // import "github.com/infobloxopen/atlas-contacts-app/pkg/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import resource "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"
import _ "github.com/infobloxopen/protoc-gen-gorm/options"
import types "github.com/infobloxopen/protoc-gen-gorm/types"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Profile struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Notes                string               `protobuf:"bytes,3,opt,name=notes" json:"notes,omitempty"`
	Contacts             []*Contact           `protobuf:"bytes,4,rep,name=contacts" json:"contacts,omitempty"`
	Groups               []*Group             `protobuf:"bytes,5,rep,name=groups" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{0}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (dst *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(dst, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Profile) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *Profile) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type CreateProfileRequest struct {
	Payload              *Profile `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProfileRequest) Reset()         { *m = CreateProfileRequest{} }
func (m *CreateProfileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProfileRequest) ProtoMessage()    {}
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{1}
}
func (m *CreateProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProfileRequest.Unmarshal(m, b)
}
func (m *CreateProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProfileRequest.Marshal(b, m, deterministic)
}
func (dst *CreateProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProfileRequest.Merge(dst, src)
}
func (m *CreateProfileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProfileRequest.Size(m)
}
func (m *CreateProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProfileRequest proto.InternalMessageInfo

func (m *CreateProfileRequest) GetPayload() *Profile {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateProfileResponse struct {
	Result               *Profile `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProfileResponse) Reset()         { *m = CreateProfileResponse{} }
func (m *CreateProfileResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProfileResponse) ProtoMessage()    {}
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{2}
}
func (m *CreateProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProfileResponse.Unmarshal(m, b)
}
func (m *CreateProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProfileResponse.Marshal(b, m, deterministic)
}
func (dst *CreateProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProfileResponse.Merge(dst, src)
}
func (m *CreateProfileResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProfileResponse.Size(m)
}
func (m *CreateProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProfileResponse proto.InternalMessageInfo

func (m *CreateProfileResponse) GetResult() *Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadProfileRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadProfileRequest) Reset()         { *m = ReadProfileRequest{} }
func (m *ReadProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ReadProfileRequest) ProtoMessage()    {}
func (*ReadProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{3}
}
func (m *ReadProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadProfileRequest.Unmarshal(m, b)
}
func (m *ReadProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadProfileRequest.Marshal(b, m, deterministic)
}
func (dst *ReadProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadProfileRequest.Merge(dst, src)
}
func (m *ReadProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ReadProfileRequest.Size(m)
}
func (m *ReadProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadProfileRequest proto.InternalMessageInfo

func (m *ReadProfileRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadProfileResponse struct {
	Result               *Profile `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadProfileResponse) Reset()         { *m = ReadProfileResponse{} }
func (m *ReadProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ReadProfileResponse) ProtoMessage()    {}
func (*ReadProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{4}
}
func (m *ReadProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadProfileResponse.Unmarshal(m, b)
}
func (m *ReadProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadProfileResponse.Marshal(b, m, deterministic)
}
func (dst *ReadProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadProfileResponse.Merge(dst, src)
}
func (m *ReadProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ReadProfileResponse.Size(m)
}
func (m *ReadProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadProfileResponse proto.InternalMessageInfo

func (m *ReadProfileResponse) GetResult() *Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateProfileRequest struct {
	Payload              *Profile `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProfileRequest) Reset()         { *m = UpdateProfileRequest{} }
func (m *UpdateProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileRequest) ProtoMessage()    {}
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{5}
}
func (m *UpdateProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileRequest.Unmarshal(m, b)
}
func (m *UpdateProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileRequest.Merge(dst, src)
}
func (m *UpdateProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileRequest.Size(m)
}
func (m *UpdateProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileRequest proto.InternalMessageInfo

func (m *UpdateProfileRequest) GetPayload() *Profile {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateProfileResponse struct {
	Result               *Profile `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProfileResponse) Reset()         { *m = UpdateProfileResponse{} }
func (m *UpdateProfileResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileResponse) ProtoMessage()    {}
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{6}
}
func (m *UpdateProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileResponse.Unmarshal(m, b)
}
func (m *UpdateProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileResponse.Merge(dst, src)
}
func (m *UpdateProfileResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileResponse.Size(m)
}
func (m *UpdateProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileResponse proto.InternalMessageInfo

func (m *UpdateProfileResponse) GetResult() *Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteProfileRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteProfileRequest) Reset()         { *m = DeleteProfileRequest{} }
func (m *DeleteProfileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProfileRequest) ProtoMessage()    {}
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{7}
}
func (m *DeleteProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProfileRequest.Unmarshal(m, b)
}
func (m *DeleteProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProfileRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProfileRequest.Merge(dst, src)
}
func (m *DeleteProfileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProfileRequest.Size(m)
}
func (m *DeleteProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProfileRequest proto.InternalMessageInfo

func (m *DeleteProfileRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ListProfilesResponse struct {
	Results              []*Profile `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProfilesResponse) Reset()         { *m = ListProfilesResponse{} }
func (m *ListProfilesResponse) String() string { return proto.CompactTextString(m) }
func (*ListProfilesResponse) ProtoMessage()    {}
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{8}
}
func (m *ListProfilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProfilesResponse.Unmarshal(m, b)
}
func (m *ListProfilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProfilesResponse.Marshal(b, m, deterministic)
}
func (dst *ListProfilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProfilesResponse.Merge(dst, src)
}
func (m *ListProfilesResponse) XXX_Size() int {
	return xxx_messageInfo_ListProfilesResponse.Size(m)
}
func (m *ListProfilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProfilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProfilesResponse proto.InternalMessageInfo

func (m *ListProfilesResponse) GetResults() []*Profile {
	if m != nil {
		return m.Results
	}
	return nil
}

type Group struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Notes                string               `protobuf:"bytes,3,opt,name=notes" json:"notes,omitempty"`
	Profile              *Profile             `protobuf:"bytes,4,opt,name=profile" json:"profile,omitempty"`
	ProfileId            *resource.Identifier `protobuf:"bytes,5,opt,name=profile_id,json=profileId" json:"profile_id,omitempty"`
	Contacts             []*Contact           `protobuf:"bytes,6,rep,name=contacts" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{9}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (dst *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(dst, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Group) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Group) GetProfileId() *resource.Identifier {
	if m != nil {
		return m.ProfileId
	}
	return nil
}

func (m *Group) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type CreateGroupRequest struct {
	Payload              *Group   `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{10}
}
func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (dst *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(dst, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetPayload() *Group {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateGroupResponse struct {
	Result               *Group   `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupResponse) Reset()         { *m = CreateGroupResponse{} }
func (m *CreateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResponse) ProtoMessage()    {}
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{11}
}
func (m *CreateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResponse.Unmarshal(m, b)
}
func (m *CreateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResponse.Marshal(b, m, deterministic)
}
func (dst *CreateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResponse.Merge(dst, src)
}
func (m *CreateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResponse.Size(m)
}
func (m *CreateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResponse proto.InternalMessageInfo

func (m *CreateGroupResponse) GetResult() *Group {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadGroupRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadGroupRequest) Reset()         { *m = ReadGroupRequest{} }
func (m *ReadGroupRequest) String() string { return proto.CompactTextString(m) }
func (*ReadGroupRequest) ProtoMessage()    {}
func (*ReadGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{12}
}
func (m *ReadGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadGroupRequest.Unmarshal(m, b)
}
func (m *ReadGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadGroupRequest.Marshal(b, m, deterministic)
}
func (dst *ReadGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadGroupRequest.Merge(dst, src)
}
func (m *ReadGroupRequest) XXX_Size() int {
	return xxx_messageInfo_ReadGroupRequest.Size(m)
}
func (m *ReadGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadGroupRequest proto.InternalMessageInfo

func (m *ReadGroupRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadGroupResponse struct {
	Result               *Group   `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadGroupResponse) Reset()         { *m = ReadGroupResponse{} }
func (m *ReadGroupResponse) String() string { return proto.CompactTextString(m) }
func (*ReadGroupResponse) ProtoMessage()    {}
func (*ReadGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{13}
}
func (m *ReadGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadGroupResponse.Unmarshal(m, b)
}
func (m *ReadGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadGroupResponse.Marshal(b, m, deterministic)
}
func (dst *ReadGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadGroupResponse.Merge(dst, src)
}
func (m *ReadGroupResponse) XXX_Size() int {
	return xxx_messageInfo_ReadGroupResponse.Size(m)
}
func (m *ReadGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadGroupResponse proto.InternalMessageInfo

func (m *ReadGroupResponse) GetResult() *Group {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateGroupRequest struct {
	Payload              *Group   `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupRequest) Reset()         { *m = UpdateGroupRequest{} }
func (m *UpdateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupRequest) ProtoMessage()    {}
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{14}
}
func (m *UpdateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupRequest.Unmarshal(m, b)
}
func (m *UpdateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupRequest.Merge(dst, src)
}
func (m *UpdateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupRequest.Size(m)
}
func (m *UpdateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupRequest proto.InternalMessageInfo

func (m *UpdateGroupRequest) GetPayload() *Group {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateGroupResponse struct {
	Result               *Group   `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupResponse) Reset()         { *m = UpdateGroupResponse{} }
func (m *UpdateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupResponse) ProtoMessage()    {}
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{15}
}
func (m *UpdateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupResponse.Unmarshal(m, b)
}
func (m *UpdateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupResponse.Merge(dst, src)
}
func (m *UpdateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupResponse.Size(m)
}
func (m *UpdateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupResponse proto.InternalMessageInfo

func (m *UpdateGroupResponse) GetResult() *Group {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteGroupRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{16}
}
func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(dst, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

func (m *DeleteGroupRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ListGroupsResponse struct {
	Results              []*Group `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{17}
}
func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (dst *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(dst, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetResults() []*Group {
	if m != nil {
		return m.Results
	}
	return nil
}

type Contact struct {
	Id           *resource.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FirstName    string               `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	MiddleName   string               `protobuf:"bytes,3,opt,name=middle_name,json=middleName" json:"middle_name,omitempty"`
	LastName     string               `protobuf:"bytes,4,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	PrimaryEmail string               `protobuf:"bytes,6,opt,name=primary_email,json=primaryEmail" json:"primary_email,omitempty"`
	Notes        string               `protobuf:"bytes,7,opt,name=notes" json:"notes,omitempty"`
	Emails       []*Email             `protobuf:"bytes,8,rep,name=emails" json:"emails,omitempty"`
	HomeAddress  *Address             `protobuf:"bytes,9,opt,name=home_address,json=homeAddress" json:"home_address,omitempty"`
	WorkAddress  *Address             `protobuf:"bytes,10,opt,name=work_address,json=workAddress" json:"work_address,omitempty"`
	ProfileId    *resource.Identifier `protobuf:"bytes,11,opt,name=profile_id,json=profileId" json:"profile_id,omitempty"`
	Profile      *Profile             `protobuf:"bytes,12,opt,name=profile" json:"profile,omitempty"`
	Groups       []*Group             `protobuf:"bytes,13,rep,name=groups" json:"groups,omitempty"`
	// nicknames is arbitrary json, but should be used for a list of strings
	Nicknames            *types.JSONValue `protobuf:"bytes,14,opt,name=nicknames" json:"nicknames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{18}
}
func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (dst *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(dst, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Contact) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Contact) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *Contact) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Contact) GetPrimaryEmail() string {
	if m != nil {
		return m.PrimaryEmail
	}
	return ""
}

func (m *Contact) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Contact) GetEmails() []*Email {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *Contact) GetHomeAddress() *Address {
	if m != nil {
		return m.HomeAddress
	}
	return nil
}

func (m *Contact) GetWorkAddress() *Address {
	if m != nil {
		return m.WorkAddress
	}
	return nil
}

func (m *Contact) GetProfileId() *resource.Identifier {
	if m != nil {
		return m.ProfileId
	}
	return nil
}

func (m *Contact) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Contact) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Contact) GetNicknames() *types.JSONValue {
	if m != nil {
		return m.Nicknames
	}
	return nil
}

type Email struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{19}
}
func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (dst *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(dst, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Email) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Address struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip" json:"zip,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{20}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (dst *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(dst, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type CreateContactRequest struct {
	Payload              *Contact `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContactRequest) Reset()         { *m = CreateContactRequest{} }
func (m *CreateContactRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContactRequest) ProtoMessage()    {}
func (*CreateContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{21}
}
func (m *CreateContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContactRequest.Unmarshal(m, b)
}
func (m *CreateContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContactRequest.Marshal(b, m, deterministic)
}
func (dst *CreateContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContactRequest.Merge(dst, src)
}
func (m *CreateContactRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContactRequest.Size(m)
}
func (m *CreateContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContactRequest proto.InternalMessageInfo

func (m *CreateContactRequest) GetPayload() *Contact {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateContactResponse struct {
	Result               *Contact `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContactResponse) Reset()         { *m = CreateContactResponse{} }
func (m *CreateContactResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContactResponse) ProtoMessage()    {}
func (*CreateContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{22}
}
func (m *CreateContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContactResponse.Unmarshal(m, b)
}
func (m *CreateContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContactResponse.Marshal(b, m, deterministic)
}
func (dst *CreateContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContactResponse.Merge(dst, src)
}
func (m *CreateContactResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContactResponse.Size(m)
}
func (m *CreateContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContactResponse proto.InternalMessageInfo

func (m *CreateContactResponse) GetResult() *Contact {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadContactRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadContactRequest) Reset()         { *m = ReadContactRequest{} }
func (m *ReadContactRequest) String() string { return proto.CompactTextString(m) }
func (*ReadContactRequest) ProtoMessage()    {}
func (*ReadContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{23}
}
func (m *ReadContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadContactRequest.Unmarshal(m, b)
}
func (m *ReadContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadContactRequest.Marshal(b, m, deterministic)
}
func (dst *ReadContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadContactRequest.Merge(dst, src)
}
func (m *ReadContactRequest) XXX_Size() int {
	return xxx_messageInfo_ReadContactRequest.Size(m)
}
func (m *ReadContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadContactRequest proto.InternalMessageInfo

func (m *ReadContactRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadContactResponse struct {
	Result               *Contact `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadContactResponse) Reset()         { *m = ReadContactResponse{} }
func (m *ReadContactResponse) String() string { return proto.CompactTextString(m) }
func (*ReadContactResponse) ProtoMessage()    {}
func (*ReadContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{24}
}
func (m *ReadContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadContactResponse.Unmarshal(m, b)
}
func (m *ReadContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadContactResponse.Marshal(b, m, deterministic)
}
func (dst *ReadContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadContactResponse.Merge(dst, src)
}
func (m *ReadContactResponse) XXX_Size() int {
	return xxx_messageInfo_ReadContactResponse.Size(m)
}
func (m *ReadContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadContactResponse proto.InternalMessageInfo

func (m *ReadContactResponse) GetResult() *Contact {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateContactRequest struct {
	Payload              *Contact `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContactRequest) Reset()         { *m = UpdateContactRequest{} }
func (m *UpdateContactRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateContactRequest) ProtoMessage()    {}
func (*UpdateContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{25}
}
func (m *UpdateContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContactRequest.Unmarshal(m, b)
}
func (m *UpdateContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContactRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContactRequest.Merge(dst, src)
}
func (m *UpdateContactRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateContactRequest.Size(m)
}
func (m *UpdateContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContactRequest proto.InternalMessageInfo

func (m *UpdateContactRequest) GetPayload() *Contact {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateContactResponse struct {
	Result               *Contact `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContactResponse) Reset()         { *m = UpdateContactResponse{} }
func (m *UpdateContactResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateContactResponse) ProtoMessage()    {}
func (*UpdateContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{26}
}
func (m *UpdateContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContactResponse.Unmarshal(m, b)
}
func (m *UpdateContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContactResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContactResponse.Merge(dst, src)
}
func (m *UpdateContactResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateContactResponse.Size(m)
}
func (m *UpdateContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContactResponse proto.InternalMessageInfo

func (m *UpdateContactResponse) GetResult() *Contact {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteContactRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteContactRequest) Reset()         { *m = DeleteContactRequest{} }
func (m *DeleteContactRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteContactRequest) ProtoMessage()    {}
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{27}
}
func (m *DeleteContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContactRequest.Unmarshal(m, b)
}
func (m *DeleteContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContactRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContactRequest.Merge(dst, src)
}
func (m *DeleteContactRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteContactRequest.Size(m)
}
func (m *DeleteContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContactRequest proto.InternalMessageInfo

func (m *DeleteContactRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ListContactsResponse struct {
	Results              []*Contact `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListContactsResponse) Reset()         { *m = ListContactsResponse{} }
func (m *ListContactsResponse) String() string { return proto.CompactTextString(m) }
func (*ListContactsResponse) ProtoMessage()    {}
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{28}
}
func (m *ListContactsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactsResponse.Unmarshal(m, b)
}
func (m *ListContactsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactsResponse.Marshal(b, m, deterministic)
}
func (dst *ListContactsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactsResponse.Merge(dst, src)
}
func (m *ListContactsResponse) XXX_Size() int {
	return xxx_messageInfo_ListContactsResponse.Size(m)
}
func (m *ListContactsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactsResponse proto.InternalMessageInfo

func (m *ListContactsResponse) GetResults() []*Contact {
	if m != nil {
		return m.Results
	}
	return nil
}

type SMSRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSRequest) Reset()         { *m = SMSRequest{} }
func (m *SMSRequest) String() string { return proto.CompactTextString(m) }
func (*SMSRequest) ProtoMessage()    {}
func (*SMSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contacts_579b8531e4c20cb3, []int{29}
}
func (m *SMSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSRequest.Unmarshal(m, b)
}
func (m *SMSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSRequest.Marshal(b, m, deterministic)
}
func (dst *SMSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSRequest.Merge(dst, src)
}
func (m *SMSRequest) XXX_Size() int {
	return xxx_messageInfo_SMSRequest.Size(m)
}
func (m *SMSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SMSRequest proto.InternalMessageInfo

func (m *SMSRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SMSRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Profile)(nil), "api.contacts.Profile")
	proto.RegisterType((*CreateProfileRequest)(nil), "api.contacts.CreateProfileRequest")
	proto.RegisterType((*CreateProfileResponse)(nil), "api.contacts.CreateProfileResponse")
	proto.RegisterType((*ReadProfileRequest)(nil), "api.contacts.ReadProfileRequest")
	proto.RegisterType((*ReadProfileResponse)(nil), "api.contacts.ReadProfileResponse")
	proto.RegisterType((*UpdateProfileRequest)(nil), "api.contacts.UpdateProfileRequest")
	proto.RegisterType((*UpdateProfileResponse)(nil), "api.contacts.UpdateProfileResponse")
	proto.RegisterType((*DeleteProfileRequest)(nil), "api.contacts.DeleteProfileRequest")
	proto.RegisterType((*ListProfilesResponse)(nil), "api.contacts.ListProfilesResponse")
	proto.RegisterType((*Group)(nil), "api.contacts.Group")
	proto.RegisterType((*CreateGroupRequest)(nil), "api.contacts.CreateGroupRequest")
	proto.RegisterType((*CreateGroupResponse)(nil), "api.contacts.CreateGroupResponse")
	proto.RegisterType((*ReadGroupRequest)(nil), "api.contacts.ReadGroupRequest")
	proto.RegisterType((*ReadGroupResponse)(nil), "api.contacts.ReadGroupResponse")
	proto.RegisterType((*UpdateGroupRequest)(nil), "api.contacts.UpdateGroupRequest")
	proto.RegisterType((*UpdateGroupResponse)(nil), "api.contacts.UpdateGroupResponse")
	proto.RegisterType((*DeleteGroupRequest)(nil), "api.contacts.DeleteGroupRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "api.contacts.ListGroupsResponse")
	proto.RegisterType((*Contact)(nil), "api.contacts.Contact")
	proto.RegisterType((*Email)(nil), "api.contacts.Email")
	proto.RegisterType((*Address)(nil), "api.contacts.Address")
	proto.RegisterType((*CreateContactRequest)(nil), "api.contacts.CreateContactRequest")
	proto.RegisterType((*CreateContactResponse)(nil), "api.contacts.CreateContactResponse")
	proto.RegisterType((*ReadContactRequest)(nil), "api.contacts.ReadContactRequest")
	proto.RegisterType((*ReadContactResponse)(nil), "api.contacts.ReadContactResponse")
	proto.RegisterType((*UpdateContactRequest)(nil), "api.contacts.UpdateContactRequest")
	proto.RegisterType((*UpdateContactResponse)(nil), "api.contacts.UpdateContactResponse")
	proto.RegisterType((*DeleteContactRequest)(nil), "api.contacts.DeleteContactRequest")
	proto.RegisterType((*ListContactsResponse)(nil), "api.contacts.ListContactsResponse")
	proto.RegisterType((*SMSRequest)(nil), "api.contacts.SMSRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfilesClient is the client API for Profiles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfilesClient interface {
	Create(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error)
	Read(ctx context.Context, in *ReadProfileRequest, opts ...grpc.CallOption) (*ReadProfileResponse, error)
	Update(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	Delete(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListProfilesResponse, error)
}

type profilesClient struct {
	cc *grpc.ClientConn
}

func NewProfilesClient(cc *grpc.ClientConn) ProfilesClient {
	return &profilesClient{cc}
}

func (c *profilesClient) Create(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error) {
	out := new(CreateProfileResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Profiles/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) Read(ctx context.Context, in *ReadProfileRequest, opts ...grpc.CallOption) (*ReadProfileResponse, error) {
	out := new(ReadProfileResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Profiles/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) Update(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Profiles/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) Delete(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.contacts.Profiles/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Profiles/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Profiles service

type ProfilesServer interface {
	Create(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error)
	Read(context.Context, *ReadProfileRequest) (*ReadProfileResponse, error)
	Update(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	Delete(context.Context, *DeleteProfileRequest) (*empty.Empty, error)
	List(context.Context, *empty.Empty) (*ListProfilesResponse, error)
}

func RegisterProfilesServer(s *grpc.Server, srv ProfilesServer) {
	s.RegisterService(&_Profiles_serviceDesc, srv)
}

func _Profiles_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Profiles/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).Create(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Profiles/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).Read(ctx, req.(*ReadProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Profiles/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).Update(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Profiles/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).Delete(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Profiles/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profiles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.contacts.Profiles",
	HandlerType: (*ProfilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Profiles_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Profiles_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Profiles_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Profiles_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Profiles_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/contacts.proto",
}

// GroupsClient is the client API for Groups service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupsClient interface {
	Create(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	Read(ctx context.Context, in *ReadGroupRequest, opts ...grpc.CallOption) (*ReadGroupResponse, error)
	Update(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error)
	Delete(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListGroupsResponse, error)
}

type groupsClient struct {
	cc *grpc.ClientConn
}

func NewGroupsClient(cc *grpc.ClientConn) GroupsClient {
	return &groupsClient{cc}
}

func (c *groupsClient) Create(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Groups/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Read(ctx context.Context, in *ReadGroupRequest, opts ...grpc.CallOption) (*ReadGroupResponse, error) {
	out := new(ReadGroupResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Groups/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Update(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error) {
	out := new(UpdateGroupResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Groups/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Delete(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.contacts.Groups/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Groups/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Groups service

type GroupsServer interface {
	Create(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	Read(context.Context, *ReadGroupRequest) (*ReadGroupResponse, error)
	Update(context.Context, *UpdateGroupRequest) (*UpdateGroupResponse, error)
	Delete(context.Context, *DeleteGroupRequest) (*empty.Empty, error)
	List(context.Context, *empty.Empty) (*ListGroupsResponse, error)
}

func RegisterGroupsServer(s *grpc.Server, srv GroupsServer) {
	s.RegisterService(&_Groups_serviceDesc, srv)
}

func _Groups_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Groups/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Create(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Groups/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Read(ctx, req.(*ReadGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Groups/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Update(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Groups/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Delete(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Groups/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Groups_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.contacts.Groups",
	HandlerType: (*GroupsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Groups_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Groups_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Groups_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Groups_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Groups_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/contacts.proto",
}

// ContactsClient is the client API for Contacts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactsClient interface {
	Create(ctx context.Context, in *CreateContactRequest, opts ...grpc.CallOption) (*CreateContactResponse, error)
	Read(ctx context.Context, in *ReadContactRequest, opts ...grpc.CallOption) (*ReadContactResponse, error)
	Update(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error)
	Delete(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListContactsResponse, error)
	SendSMS(ctx context.Context, in *SMSRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type contactsClient struct {
	cc *grpc.ClientConn
}

func NewContactsClient(cc *grpc.ClientConn) ContactsClient {
	return &contactsClient{cc}
}

func (c *contactsClient) Create(ctx context.Context, in *CreateContactRequest, opts ...grpc.CallOption) (*CreateContactResponse, error) {
	out := new(CreateContactResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Contacts/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Read(ctx context.Context, in *ReadContactRequest, opts ...grpc.CallOption) (*ReadContactResponse, error) {
	out := new(ReadContactResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Contacts/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Update(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error) {
	out := new(UpdateContactResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Contacts/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) Delete(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.contacts.Contacts/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	out := new(ListContactsResponse)
	err := c.cc.Invoke(ctx, "/api.contacts.Contacts/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactsClient) SendSMS(ctx context.Context, in *SMSRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.contacts.Contacts/SendSMS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Contacts service

type ContactsServer interface {
	Create(context.Context, *CreateContactRequest) (*CreateContactResponse, error)
	Read(context.Context, *ReadContactRequest) (*ReadContactResponse, error)
	Update(context.Context, *UpdateContactRequest) (*UpdateContactResponse, error)
	Delete(context.Context, *DeleteContactRequest) (*empty.Empty, error)
	List(context.Context, *empty.Empty) (*ListContactsResponse, error)
	SendSMS(context.Context, *SMSRequest) (*empty.Empty, error)
}

func RegisterContactsServer(s *grpc.Server, srv ContactsServer) {
	s.RegisterService(&_Contacts_serviceDesc, srv)
}

func _Contacts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Create(ctx, req.(*CreateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Read(ctx, req.(*ReadContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Update(ctx, req.(*UpdateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).Delete(ctx, req.(*DeleteContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contacts_SendSMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).SendSMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.contacts.Contacts/SendSMS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).SendSMS(ctx, req.(*SMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Contacts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.contacts.Contacts",
	HandlerType: (*ContactsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Contacts_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Contacts_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Contacts_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Contacts_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Contacts_List_Handler,
		},
		{
			MethodName: "SendSMS",
			Handler:    _Contacts_SendSMS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/contacts.proto",
}

func init() { proto.RegisterFile("pkg/pb/contacts.proto", fileDescriptor_contacts_579b8531e4c20cb3) }

var fileDescriptor_contacts_579b8531e4c20cb3 = []byte{
	// 1540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x5f, 0x6f, 0xdb, 0x54,
	0x14, 0x9f, 0xd3, 0x34, 0x7f, 0x4e, 0xbb, 0xae, 0xbb, 0xeb, 0x36, 0xd7, 0xdb, 0x58, 0x66, 0x84,
	0x34, 0xb5, 0x24, 0xde, 0xb2, 0xf1, 0x67, 0xad, 0x90, 0xb6, 0x74, 0xa3, 0xda, 0xc4, 0x06, 0xa4,
	0x1a, 0x0f, 0x93, 0x50, 0x71, 0xe2, 0xdb, 0xf4, 0xae, 0x8e, 0xaf, 0xf1, 0x75, 0x18, 0x05, 0x4d,
	0x42, 0x20, 0xf1, 0x01, 0xe0, 0x85, 0x07, 0x5e, 0x79, 0xe2, 0x13, 0x34, 0x4f, 0xbc, 0xf2, 0x0a,
	0x7c, 0x04, 0x5e, 0xf8, 0x10, 0x48, 0xc8, 0xf7, 0x8f, 0xe3, 0x38, 0x4e, 0x9a, 0x65, 0xe3, 0x25,
	0xb2, 0x7d, 0xcf, 0x39, 0xbf, 0x73, 0xce, 0xfd, 0x9d, 0x73, 0xcf, 0x0d, 0x9c, 0xf5, 0x0f, 0x3a,
	0x96, 0xdf, 0xb2, 0xda, 0xd4, 0x0b, 0xed, 0x76, 0xc8, 0x6a, 0x7e, 0x40, 0x43, 0x8a, 0x16, 0x6d,
	0x9f, 0xd4, 0xd4, 0x37, 0xe3, 0x42, 0x87, 0xd2, 0x8e, 0x8b, 0x2d, 0xbe, 0xd6, 0xea, 0xed, 0x59,
	0xb8, 0xeb, 0x87, 0x87, 0x42, 0xd4, 0xb8, 0x28, 0x17, 0x6d, 0x9f, 0x58, 0xb6, 0xe7, 0xd1, 0xd0,
	0x0e, 0x09, 0xf5, 0xa4, 0x21, 0x63, 0xb3, 0x43, 0xc2, 0xfd, 0x5e, 0xab, 0xd6, 0xa6, 0x5d, 0xcb,
	0x3d, 0xdc, 0x0b, 0x85, 0x8d, 0x76, 0xb5, 0x83, 0xbd, 0xea, 0x17, 0xb6, 0x4b, 0x1c, 0x3b, 0xc4,
	0xd6, 0xc8, 0x83, 0x54, 0x7e, 0x33, 0x21, 0xcc, 0x9e, 0xd9, 0x9d, 0x0e, 0x0e, 0x2c, 0xea, 0x73,
	0xf3, 0x19, 0x50, 0x1b, 0x09, 0x28, 0xe2, 0xed, 0xd1, 0x96, 0x4b, 0xbf, 0xa4, 0x3e, 0xf6, 0x92,
	0x90, 0x1d, 0x1a, 0x74, 0x63, 0x13, 0xd1, 0x8b, 0xd4, 0xbd, 0x35, 0xad, 0x6e, 0x78, 0xe8, 0x63,
	0x26, 0x7e, 0xa5, 0xea, 0xbd, 0x71, 0xaa, 0x76, 0xe8, 0xda, 0xac, 0x6a, 0xfb, 0x7e, 0x35, 0xa4,
	0xd4, 0x3d, 0x20, 0xa1, 0x15, 0xf8, 0x6d, 0x2b, 0xc0, 0x8c, 0xf6, 0x82, 0x36, 0x8e, 0x1f, 0x84,
	0x19, 0xf3, 0x2f, 0x0d, 0x8a, 0x1f, 0x05, 0x74, 0x8f, 0xb8, 0x18, 0xbd, 0x05, 0x39, 0xe2, 0xe8,
	0x5a, 0x45, 0xbb, 0xba, 0x50, 0x3f, 0x5b, 0xe3, 0x76, 0x6a, 0x81, 0xdf, 0xae, 0xdd, 0x77, 0xb0,
	0x17, 0x92, 0x3d, 0x82, 0x83, 0xc6, 0x52, 0xff, 0x68, 0x15, 0xa0, 0x84, 0x0a, 0x0c, 0x07, 0xc4,
	0x76, 0x9b, 0x39, 0xe2, 0x20, 0x04, 0x79, 0xcf, 0xee, 0x62, 0x3d, 0x57, 0xd1, 0xae, 0x96, 0x9b,
	0xfc, 0x19, 0xad, 0xc0, 0xbc, 0x47, 0x43, 0xcc, 0xf4, 0x39, 0xfe, 0x51, 0xbc, 0xa0, 0xeb, 0x50,
	0x52, 0x9b, 0xab, 0xe7, 0x2b, 0x73, 0x02, 0x26, 0xb1, 0xe3, 0xb5, 0x2d, 0xf1, 0xd0, 0x8c, 0xc5,
	0xd0, 0x3a, 0x14, 0x3a, 0x01, 0xed, 0xf9, 0x4c, 0x9f, 0xe7, 0x0a, 0x67, 0x86, 0x15, 0xb6, 0xa3,
	0xb5, 0xa6, 0x14, 0xd9, 0x28, 0xf5, 0x8f, 0x56, 0xf3, 0x25, 0xad, 0xa2, 0x99, 0xdb, 0xb0, 0xb2,
	0x15, 0x60, 0x3b, 0xc4, 0x32, 0xb6, 0x26, 0xfe, 0xbc, 0x87, 0x59, 0x88, 0x2c, 0x28, 0xfa, 0xf6,
	0xa1, 0x4b, 0xed, 0x44, 0x9c, 0x49, 0x7b, 0x4a, 0x5c, 0x49, 0x99, 0xef, 0xc3, 0xd9, 0x94, 0x21,
	0xe6, 0x53, 0x8f, 0x61, 0x54, 0x85, 0x42, 0x80, 0x59, 0xcf, 0x0d, 0x27, 0x1b, 0x92, 0x42, 0xe6,
	0x26, 0xa0, 0x26, 0xb6, 0x9d, 0x94, 0x3b, 0x6f, 0x1c, 0x9b, 0xf1, 0x28, 0xc3, 0xe6, 0x5d, 0x38,
	0x33, 0xa4, 0x3c, 0x9b, 0x0b, 0xdb, 0xb0, 0xf2, 0xd8, 0x77, 0x5e, 0x4d, 0x4e, 0x52, 0x86, 0x66,
	0x73, 0xe8, 0x3d, 0x58, 0xb9, 0x8b, 0x5d, 0x3c, 0xe2, 0xd0, 0x94, 0x59, 0xd9, 0x86, 0x95, 0x0f,
	0x08, 0x0b, 0xa5, 0x32, 0x8b, 0xbd, 0xb0, 0xa0, 0x28, 0x00, 0x98, 0xae, 0x65, 0x91, 0x2c, 0x8e,
	0x47, 0x4a, 0x99, 0x3f, 0xe7, 0x60, 0x9e, 0x13, 0xe9, 0xff, 0xaf, 0x80, 0x77, 0xa0, 0xe8, 0x0b,
	0x78, 0x3d, 0x3f, 0x21, 0x45, 0x8d, 0x42, 0xff, 0x68, 0x35, 0x67, 0x9e, 0x68, 0x2a, 0x69, 0x74,
	0x13, 0x40, 0x3e, 0xee, 0x12, 0x47, 0x9f, 0x9f, 0x94, 0x9b, 0xb2, 0x14, 0xbc, 0xef, 0xa0, 0x5b,
	0x89, 0x82, 0x2b, 0x4c, 0x28, 0x38, 0x81, 0x57, 0x3f, 0x31, 0x28, 0xbc, 0x44, 0x2d, 0x6d, 0x01,
	0x12, 0x25, 0x20, 0x8a, 0x4d, 0x6e, 0x52, 0x35, 0xcd, 0x9a, 0xcc, 0xca, 0x8c, 0x39, 0xd3, 0x80,
	0x33, 0x43, 0x46, 0xe4, 0x5e, 0xad, 0xa7, 0x18, 0x93, 0x5d, 0xde, 0x92, 0x2f, 0xb7, 0x60, 0x39,
	0x2a, 0x83, 0x21, 0x37, 0xa6, 0xe4, 0xca, 0x6d, 0x38, 0x9d, 0x50, 0x9d, 0x05, 0x7c, 0x0b, 0x90,
	0x20, 0xfd, 0x4b, 0x66, 0x61, 0xc8, 0xc8, 0x2c, 0x8e, 0x6c, 0x02, 0x12, 0x55, 0x33, 0x4b, 0x1e,
	0xb6, 0x00, 0x45, 0x35, 0xc3, 0x55, 0x59, 0xa2, 0x6e, 0x53, 0x15, 0x93, 0x1d, 0x85, 0xaa, 0x97,
	0x7f, 0xf3, 0x50, 0x94, 0xc4, 0x99, 0xb5, 0x62, 0x2e, 0x01, 0xec, 0x91, 0x80, 0x85, 0xbb, 0x89,
	0xba, 0x29, 0xf3, 0x2f, 0x8f, 0xa2, 0xe2, 0xb9, 0x0c, 0x0b, 0x5d, 0xe2, 0x38, 0x2e, 0x16, 0xeb,
	0xa2, 0x84, 0x40, 0x7c, 0xe2, 0x02, 0x17, 0xa0, 0xec, 0xda, 0x4a, 0x3d, 0xcf, 0x97, 0x4b, 0xd1,
	0x07, 0xbe, 0x78, 0x13, 0x4e, 0xfa, 0x01, 0xe9, 0xda, 0xc1, 0xe1, 0x2e, 0xee, 0xda, 0xc4, 0xd5,
	0x0b, 0x91, 0x40, 0xe3, 0x54, 0xc4, 0xf1, 0x65, 0xad, 0xff, 0xcf, 0x6f, 0x73, 0xf9, 0x20, 0xf7,
	0x99, 0xd6, 0x5c, 0x94, 0x52, 0xf7, 0x22, 0xa1, 0x41, 0xc1, 0x16, 0x93, 0x05, 0xbb, 0x0e, 0x05,
	0x6e, 0x83, 0xe9, 0xa5, 0xac, 0xcc, 0x70, 0xd5, 0xa6, 0x14, 0x41, 0xef, 0xc2, 0xe2, 0x3e, 0xed,
	0xe2, 0x5d, 0xdb, 0x71, 0x02, 0xcc, 0x98, 0x5e, 0xce, 0x2a, 0xf1, 0x3b, 0x62, 0xb1, 0xb9, 0x10,
	0x89, 0xca, 0x97, 0x48, 0xf3, 0x19, 0x0d, 0x0e, 0x62, 0x4d, 0x98, 0xa8, 0x19, 0x89, 0x2a, 0xcd,
	0xe1, 0xc6, 0xb0, 0x30, 0x65, 0x63, 0x48, 0xf4, 0xa1, 0xc5, 0x17, 0xea, 0x43, 0x5b, 0xf1, 0x79,
	0x7c, 0x72, 0x2c, 0x53, 0x1a, 0xe7, 0xfa, 0x47, 0xab, 0xa8, 0xbe, 0x0c, 0x4b, 0x5c, 0x74, 0x57,
	0xad, 0xaa, 0x73, 0x1a, 0xdd, 0x80, 0xb2, 0x47, 0xda, 0x07, 0xd1, 0xe6, 0x31, 0x7d, 0x49, 0xe2,
	0xf3, 0xb1, 0x48, 0x4c, 0x38, 0x0f, 0x76, 0x3e, 0x7c, 0xf4, 0x89, 0xed, 0xf6, 0x70, 0x73, 0x20,
	0x97, 0x68, 0x48, 0x2d, 0x98, 0x17, 0x5b, 0xb6, 0x14, 0x93, 0x2f, 0xcf, 0x59, 0xb5, 0x0e, 0x45,
	0x95, 0x40, 0x4e, 0xa9, 0xc6, 0xe9, 0x48, 0x07, 0x72, 0xd7, 0x12, 0x9b, 0xae, 0x24, 0x36, 0x2e,
	0xf6, 0x8f, 0x56, 0xf5, 0x92, 0x16, 0x35, 0xef, 0x16, 0xa5, 0x2e, 0x02, 0xc2, 0x76, 0x25, 0x21,
	0x2a, 0x9a, 0xf9, 0x9d, 0x06, 0x45, 0x95, 0x62, 0x7d, 0x60, 0x56, 0xe3, 0xdc, 0x50, 0xaf, 0x91,
	0x6e, 0x9b, 0x84, 0x87, 0xaa, 0xf1, 0x47, 0xcf, 0x11, 0x8f, 0x58, 0x68, 0x87, 0x8a, 0xb5, 0xe2,
	0x05, 0x2d, 0xc3, 0xdc, 0x57, 0xc4, 0x97, 0x54, 0x8d, 0x1e, 0x23, 0xab, 0x6d, 0xda, 0xf3, 0xc2,
	0xe0, 0x90, 0xb7, 0xf3, 0x72, 0x53, 0xbd, 0x66, 0x8d, 0x31, 0x6a, 0x30, 0x9a, 0xf2, 0xc8, 0x56,
	0xe2, 0xa3, 0x63, 0x4c, 0x6c, 0x68, 0xba, 0x23, 0x5b, 0x89, 0xa7, 0xc6, 0x98, 0x94, 0x3b, 0x2f,
	0x36, 0xc6, 0xbc, 0xa4, 0x0b, 0xf1, 0x18, 0xf3, 0x0a, 0x72, 0x92, 0x32, 0x34, 0x9b, 0x43, 0xf1,
	0x18, 0x33, 0x5b, 0x56, 0xe4, 0x18, 0xb3, 0xa5, 0x8a, 0x64, 0xda, 0x31, 0x26, 0x8e, 0x47, 0xb5,
	0xe5, 0xb7, 0x01, 0x76, 0x1e, 0xee, 0x28, 0xf4, 0x74, 0x6d, 0xe8, 0x50, 0xec, 0x62, 0xc6, 0xec,
	0x8e, 0x6a, 0xb7, 0xea, 0xb5, 0xfe, 0x7b, 0x1e, 0x4a, 0x6a, 0x88, 0x42, 0x5d, 0x28, 0x08, 0xa2,
	0x20, 0x33, 0x05, 0x97, 0x31, 0x4e, 0x1b, 0xaf, 0x4f, 0x94, 0x11, 0x81, 0x98, 0xc6, 0xb7, 0x7f,
	0xfe, 0xfd, 0x63, 0x6e, 0xc5, 0x2c, 0x5b, 0xb2, 0x89, 0xb0, 0x0d, 0xb5, 0x07, 0x88, 0x42, 0x3e,
	0xa2, 0x04, 0xaa, 0x0c, 0x1b, 0x1a, 0x1d, 0x95, 0x8d, 0x2b, 0x13, 0x24, 0x24, 0x90, 0xc9, 0x81,
	0x2e, 0x22, 0x23, 0x06, 0xb2, 0xbe, 0x26, 0x4e, 0x4d, 0xdd, 0x78, 0x76, 0x89, 0xf3, 0x1c, 0x7d,
	0xaf, 0x41, 0x41, 0xec, 0x7a, 0x3a, 0xc0, 0xac, 0xd9, 0x38, 0x1d, 0x60, 0xe6, 0xd8, 0x6b, 0xde,
	0xe0, 0xb8, 0x55, 0xc3, 0x4c, 0xe0, 0xca, 0x00, 0x6b, 0x29, 0xfc, 0x41, 0xe4, 0x3d, 0x28, 0x08,
	0xd6, 0xa4, 0xfd, 0xc8, 0x1a, 0x89, 0x8d, 0x73, 0x35, 0x71, 0xdd, 0xad, 0xa9, 0xbb, 0x70, 0xed,
	0x5e, 0x74, 0x17, 0x36, 0xad, 0xfe, 0xd1, 0x6a, 0x39, 0xbe, 0xc1, 0x89, 0xf8, 0xd7, 0x26, 0xc5,
	0xff, 0x18, 0xf2, 0x11, 0xdb, 0xd0, 0x18, 0x83, 0x46, 0xca, 0x99, 0xac, 0x01, 0xdb, 0x3c, 0xcd,
	0x71, 0x16, 0xd0, 0x60, 0x43, 0x0d, 0x7e, 0x4e, 0x94, 0xb4, 0xfa, 0xaf, 0x79, 0x28, 0x88, 0xe1,
	0x02, 0x75, 0x62, 0x26, 0x55, 0xb2, 0x58, 0x92, 0x9c, 0x5e, 0xd2, 0x9b, 0x9b, 0x31, 0x29, 0x9a,
	0x3a, 0x07, 0x45, 0x66, 0xd1, 0x92, 0x97, 0xbd, 0x38, 0x93, 0x44, 0x72, 0xe8, 0xb5, 0x51, 0x86,
	0x0c, 0x81, 0x5c, 0x1e, 0xbb, 0x2e, 0x21, 0x2a, 0x1c, 0xc2, 0x40, 0xba, 0x84, 0x18, 0xcd, 0xde,
	0x37, 0x03, 0xf6, 0x54, 0xb2, 0x98, 0x31, 0x29, 0xa8, 0x8c, 0xc1, 0xcf, 0xbc, 0xce, 0x11, 0xd7,
	0x8d, 0x4a, 0x8c, 0x78, 0x2c, 0x6f, 0x68, 0xcc, 0x9b, 0x4a, 0x16, 0x6f, 0x86, 0x3c, 0x18, 0xc7,
	0x9a, 0xf5, 0xfe, 0xd1, 0x6a, 0x51, 0xde, 0x79, 0x44, 0xcc, 0x6b, 0xe3, 0x63, 0xfe, 0xf8, 0x18,
	0xc6, 0x54, 0x46, 0x19, 0x33, 0x3c, 0x5e, 0x9a, 0xa7, 0x38, 0x46, 0x19, 0xa9, 0xad, 0x8b, 0xd9,
	0xf2, 0xcb, 0x3c, 0x94, 0x54, 0xdf, 0x3b, 0xae, 0xf3, 0x0c, 0x37, 0xd7, 0xec, 0xce, 0x93, 0x6a,
	0xe4, 0x89, 0xce, 0x13, 0x5f, 0x6b, 0xa6, 0xe9, 0x3c, 0x29, 0xa8, 0x2b, 0x13, 0x24, 0x46, 0x3a,
	0x8f, 0x12, 0x7b, 0xf1, 0xce, 0x33, 0x39, 0xc0, 0xcc, 0x93, 0x2a, 0xd1, 0x79, 0x06, 0xb8, 0x2f,
	0xdb, 0x79, 0x52, 0x7e, 0x1c, 0xd3, 0x79, 0xa4, 0x74, 0xdc, 0x79, 0xc6, 0xc7, 0x3f, 0x43, 0xe7,
	0x49, 0x9f, 0x89, 0x89, 0xce, 0x13, 0xff, 0x41, 0xf4, 0x04, 0x8a, 0x3b, 0xd8, 0x73, 0x76, 0x1e,
	0xee, 0x20, 0x7d, 0xd8, 0xc2, 0xe0, 0x30, 0x1c, 0x1b, 0xc4, 0x25, 0x6e, 0xef, 0xbc, 0x89, 0x86,
	0xfc, 0x7e, 0x6e, 0xb1, 0x2e, 0xdb, 0xd0, 0xd6, 0x14, 0x4f, 0x1b, 0x7f, 0x68, 0x3f, 0xdc, 0xf9,
	0x49, 0x43, 0xde, 0x80, 0xad, 0xe6, 0xa7, 0xb0, 0xf4, 0x80, 0xee, 0x7b, 0x95, 0x06, 0x76, 0xed,
	0xae, 0x1d, 0x90, 0x36, 0xaa, 0xef, 0x87, 0xa1, 0xcf, 0x36, 0x2c, 0x6b, 0xf2, 0x1f, 0x73, 0x0a,
	0xa8, 0x6a, 0xfb, 0xbe, 0x71, 0xfe, 0x69, 0x4b, 0xe9, 0xdf, 0x56, 0xb2, 0x91, 0x62, 0x7d, 0xee,
	0x7a, 0xed, 0xda, 0x5a, 0x4e, 0xcb, 0xd5, 0x97, 0x6d, 0xdf, 0x77, 0x49, 0x9b, 0xff, 0xe3, 0x68,
	0x3d, 0x65, 0xd4, 0xdb, 0x18, 0xf9, 0xf2, 0xe4, 0xe6, 0xf4, 0x88, 0x96, 0xf8, 0xdf, 0x75, 0xd3,
	0x6f, 0xb5, 0x0a, 0x3c, 0x17, 0x37, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x81, 0xd0, 0x65,
	0x8b, 0x15, 0x00, 0x00,
}
